### ISSUE TITLE
Spec support for animation

### ISSUE THREAD

**Issue by arvind** [vega/vega-embed#1]
It would be useful to also be able to specify animation options as part of an embedding specification. 

(And, perhaps all other options that `vg.parse.spec` takes, as well? That way, you could completely control a standalone vega specification (including passing other data options) via a vega-embed specification.)

**Comment by jheer** [comment]
Sounds good to me. PRs welcome!

**Comment by owendall** [comment]
Great Idea.  +1.  I will see if I can find a recruit since this has been open for a year. :-)

**Comment by domoritz** [comment]
Needs Vega support first.
