### ISSUE TITLE
Support copy image to clipboard

### ISSUE THREAD

**Issue by kanitw** [vega/vega-embed#10]
We support export to png, which requires saving it to disk first.  
Another useful option would be copy to clipboard.

**Comment by domoritz** [comment]
Right click on canvas?

**Comment by kanitw** [comment]
Oh true, but this isn't supported for svg.  Our Vega-Lite tutorials somehow use svg https://vega.github.io/vega-lite/tutorials/explore.html.

**Comment by domoritz** [comment]
I guess svg scales better.

**Comment by domoritz** [comment]
Closing as the solution for canvas is to left click. We will add export functionality to the editor.
