### ISSUE TITLE
Set the filename of a chart created when clicking "Save as PNG"

### ISSUE THREAD

**Issue by BenSandeen** [vega/vega-embed#102]
Our project occasionally needs us to save charts. While we have a script that can save all our charts automatically, sometimes we just want to save a handful at a time (we have a lot of charts, so this is much faster than running the script to save all charts). However, it's quite inconvenient that they all get saved as "visualization.png", since we then have rename each file as we save it.

It looks like the filename is hardcoded to "visualization.png" in https://github.com/vega/vega-embed/blob/784ae0a47b93ce343301d0bde40707f3052d68b1/src/embed.ts#L313.  Can this be changed to allow for user configuration?

**Comment by domoritz** [comment]
Do I understand it correctly that you want to programmatically generate and save a bunch of charts? You can just call `view.toImageURL(...)` then. 

Having said that, I'm happy to accept a PR that adds the option to customize the file name.

**Comment by BenSandeen** [comment]
Thanks for the stupidly fast response! :P I'll look into `view.toImageURL`.  For what it's worth, I'm not using this repo directly, but rather I'm using it via https://github.com/altair-viz/altair.  I'll see if I can figure out how to get `view.toImageURL` in there somehow.

**Comment by domoritz** [comment]
Oh yeah, for Altair you'll need a new option so that you can set it from Python (you don't have access to the view from Python). That makes me think that we really should have this option.

**Comment by domoritz** [comment]
@BenSandeen Can you send a PR?

**Comment by g3o2** [comment]
How about giving it the name of the spec file, i.e. the name before the `.` character ?

**Comment by domoritz** [comment]
We don't always have that but we could use it if we have a URL.

**Comment by domoritz** [comment]
We have downloadFileName now.
