### ISSUE TITLE
Can not use it in Electron

### ISSUE THREAD

**Issue by Jocs** [vega/vega-embed#103]
First of all, thank you very much for providing such an excellent library.

When I was using it in Electron, I started the Electron app and the console reported the following error:

```sh
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
    Referenced from: /Users/ransixi/Documents/marktext/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node
    Expected in: flat namespace

  dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
    Referenced from: /Users/ransixi/Documents/marktext/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node
    Expected in: flat namespace
```

I can be sure that the error is caused by `vega-embed`, but I don't know how to fix it? Do you know?

**Comment by Jocs** [comment]
OS version: macOs 10.14.1 (18B75)
vega-embed version: 3.23.1

**Comment by domoritz** [comment]
I don't know how to help and the issue does not point at Vega-Embed directly. I'll close this issue as I don't have anything to say but feel free to respond to this issue.

**Comment by kristw** [comment]
Not sure if this will be useful, but [vega-desktop](https://github.com/vega/vega-desktop) is an Electron app for vega. You might find example usage there.

**Comment by Jocs** [comment]
@kristw thanks, I'll take a look.

**Comment by Jocs** [comment]
@domoritz Sorry for I paste the wrong error message, I have updated it in the issue description.
