### ISSUE TITLE
Allow setting the `scaleFactor` for each format separately

### ISSUE THREAD

**Issue by joaopalmeiro** [vega/vega-embed#1047]
Hi! 👋 

Given that there are two possible formats for exporting a chart image (PNG and SVG), one of which is a vector format (SVG), I think it would be interesting to offer some more flexibility in choosing the `scaleFactor`. 

Thus, the user could choose two different values, scaling the PNG format to obtain a higher quality image and leaving the SVG `scaleFactor` with the default value, for example. Until today, every time I set the `scaleFactor` it was precisely to export larger PNG images, but I would like to keep the original width and height for the SVG format. 

For example, the `scaleFactor` could be a `Number / Object`, where a `Number` would define the `scaleFactor` for both formats and an `Object` would allow choosing the value for each format.

What do you think of this idea? If you find the idea interesting, let me know if I can help and contribute! 😄

**Comment by domoritz** [comment]
I think this is a good idea and I would be happy to review a pull request.

**Comment by joaopalmeiro** [comment]
Ready for review, @domoritz. Thanks for the opportunity! 😄
