### ISSUE TITLE
"View Vega" in the menu sounds ambiguous 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-embed#110]
Do you mean "View Vega Source"?

**Comment by domoritz** [comment]
Yes. It's a bit long and it's not hard to guess. You can override it for your app as well.

**Comment by kanitw** [comment]
It's not that long.  Better be clear for good UX.  

For example, 

<img width="184" alt="image" src="https://user-images.githubusercontent.com/111269/49319584-57407c00-f4b2-11e8-936e-3868905e44e0.png">

"View Vega Source" is as long as "Show Page Source" in Safari.

**Comment by kanitw** [comment]
"View Vega Source"

is even shorter than 

"Open in Vega Editor"

**Comment by domoritz** [comment]
Great. Let's change it.
