### ISSUE TITLE
Tooltips do not show when embedding directly in document.body

### ISSUE THREAD

**Issue by marcprux** [vega/vega-embed#113]
When you embed a visualization directly in a document's body (useful for visualizations that will be shown in an iframe), the spec is rendered fine, but tooltips don't appear at all: `vegaEmbed(document.body, spec)`.

I expect this is because tooltips are rendered by creating a peer element to the target container, which works for `<body><div/></body>`, but won't work with the top-level body. This is perhaps a reasonable limitation, but there is no warning or other indication of why tooltips aren't being rendered, so perhaps an acceptable solution would be to mitigate the confusion with documentation and warnings (or just prohibit rendering to the document body at all).

**Comment by domoritz** [comment]
Good catch. Can you send a PR?

**Comment by domoritz** [comment]
This seems to work for me. Please reopen with an example if it doesn't work.
