### ISSUE TITLE
Support embedding in Shadow DOM

### ISSUE THREAD

**Issue by Buroni** [vega/vega-embed#1135]
Currently vega charts can't be embedded inside web components with shadow DOM, as the `vegaEmbed` selector seems to only search the `document` level.

It would be great if a shadow root could be specified in `vegaEmbed` via selecting its custom element, e.g.

```js
await vegaEmbed(
    '#el-inside-web-component', 
    json, 
    {
        mode: 'vega-lite',
        root: 'my-web-component#foo'
    },
);
```

**Comment by domoritz** [comment]
Thanks for the issue. I'm not Samia liar with shadow Dom. Can  you send a pull request with tests?

**Comment by Buroni** [comment]
Hey @domoritz, I just realised that the first parameter of `vegaEmbed` accepts a DOM object as well as a string. So I could achieve the same thing with

```javascript
await vegaEmbed(
    document.querySelector('my-web-component#foo').shadowRoot.querySelector('#el-inside-web-component'),
    json,
    { mode: 'vega-lite'},
);
```

Closing as I think that's sufficient to solve the problem I was facing.
