### ISSUE TITLE
vega-lite package.json module requires undeclared vega

### ISSUE THREAD

**Issue by erikjchan** [vega/vega-embed#114]
The `package.json` uses v3.0.0-rc9, but should be updated to v3.0.0-rc10. There was a bug (https://github.com/vega/vega-lite/issues/4339) where, if you import vega-embed into a file that gets webpacked, you get a complaint about not being to find vega.

So, the line `"vega-lite": "^3.0.0-rc9 || ^2.6.0",` should be changed to `"vega-lite": "^3.0.0-rc10 || ^2.6.0",`.

**Comment by domoritz** [comment]
Thanks. Fixed and released.
