### ISSUE TITLE
Url configuration parameters

### ISSUE THREAD

**Issue by domoritz** [vega/vega-embed#12]
@ellisonbg and @jakevdp would like to pass parameters related to data loading (baseurl, ...) through vega-embed.  

To resolve this, we just have to pass the right options to https://github.com/vega/datalib/wiki/Import#dl_load in https://github.com/vega/vega-embed/blob/master/src/embed.js#L28

**Comment by arvind** [comment]
For now, one option is to modify `vg.config` prior to the `vg.embed` call like we do [in the editor](https://github.com/vega/vega-editor/blob/master/app/editor.js#L371).

**Comment by domoritz** [comment]
You can customize the loader. Embed now respects the config.
