### ISSUE TITLE
get the click event of the axis `tick label`

### ISSUE THREAD

**Issue by Liripo** [vega/vega-embed#1267]
I want to try to get the click event of the axis `tick label`. 

But when I get the click event, the item is ` undefined`, and I have no way of knowing which axis label  I clicked.
![image](https://github.com/vega/vega-embed/assets/54770415/98706d92-75d4-4d4c-80f1-e17ac041fbc2)

```js
view.addEventListener('click', function(event, item) {
      console.log('CLICK', event, item);
 });
```

**Comment by domoritz** [comment]
This would be a question about Vega itself rather than Vega embed.
