### ISSUE TITLE
vega-embed is missing a bundled dependency yallist

### ISSUE THREAD

**Issue by mvshmakov** [vega/vega-embed#1279]
When installing the `vega-embed` with `yarn`, it produces the following warning:

```txt
warning "vega-embed@6.23.0" is missing a bundled dependency "yallist". This should be reported to the package maintainer.
```

Packages info:
- node: v20.9.0
- yarn: v1.22.19
- vega: v5.22.1
- vega-lite: v5.6.0
- vega-embed: 6.23.0

**Comment by domoritz** [comment]
I think that should be okay and is there to fix a build error: https://github.com/vega/vega-embed/issues/780. As long as you don't see a failure, I think you can ignore the warning.

**Comment by domoritz** [comment]
If you have cycles to check whether we still need to include the bundled dep, that would be awesome.

**Comment by domoritz** [comment]
Closing since there is no visible error.
