### ISSUE TITLE
Version jump?

### ISSUE THREAD

**Issue by domoritz** [vega/vega-embed#128]
Should Vega-Embed jump to version 4 if we support add Vega 5 as a supported dependency? I could go either way since Embed itself won't change but people who depend on a major version of Embed will not necessarily know that they are pulling in a newer version of Vega. Either way, I will wait with the update until Vega-Lite supports Vega 5. 

Opinions @kanitw @jheer @arvind?

**Comment by g3o2** [comment]
Is there any vega version that the current vega-embed version no longer supports? If yes, that version could have been considered a breaking version change. Features not working with older versions but which are otherwise still supported should throw an error or warning instead.

**Comment by domoritz** [comment]
Embed does not change but Vega and Vega-Lite have breaking changes in the next versions.

**Comment by g3o2** [comment]
Exactly, therefore I think a minor version change of vega-embed should be enough: new feature = added support for the new versions of vega-lite and vega.

**Comment by g3o2** [comment]
> they are pulling in a newer version of Vega

Ah, on second thought, I see what you mean.

**Comment by domoritz** [comment]
I decided to make a few other changes so I will make it a 4.0 release.
