### ISSUE TITLE
optionally view compiled vega source for vega-lite specs

### ISSUE THREAD

**Issue by g3o2** [vega/vega-embed#13]
It would be nice if the viewSource action button could also be set to view the **compiled vega source** for displays generated with vega-lite. I sometimes use vega-lite to build a rough design and then continue with Vega for the fine-tuning.

Currently, I work around this with the following code, which allows me to put the Vega compiled source underneath the display:

```
    vg.embed("#vis", my_embed_spec, function(error, result) {
        if (error) throw error; // if there are problems with the file, check the error log        

        // show compiled vega source for vl specifications
        var mycode = d3.select('#source');
        mycode.append('pre')
            .append('code')
            .attr('class', 'json')
            .text(JSON.stringify(result.spec, null, 2));
    });
```

**Comment by domoritz** [comment]
Another workaround is to go to the vega editor, which shows the vega code in a panel below the vega-lite code. 

<img width="848" alt="screen shot 2016-09-27 at 09 31 14" src="https://cloud.githubusercontent.com/assets/589034/18882696/293bfa08-8495-11e6-8fed-a70322bf7310.png">

**Comment by domoritz** [comment]
I guess we could add another action for this (but turn it off by default). @g3o2 could you send a PR?

**Comment by g3o2** [comment]
hmm, ok, if you wish it so, consider though that I'm only a rookie in js programming. Is there an existing function from which i can inspire myself ?

**Comment by domoritz** [comment]
Yes, look at the action to view the source. Thanks!
