### ISSUE TITLE
Confounded height calculation?

### ISSUE THREAD

**Issue by jheer** [vega/vega-embed#131]
I'm using Altair in Colab and seeing a sizing issue, where the output cell is inappropriately sized and the bottom chart content is being cut-off, requiring scrolling. (See image below.) Upon first glance this appears to be a result of the vega-embed action menu being located at a position higher then the chart itself.

![image](https://user-images.githubusercontent.com/202799/53539749-af921480-3ac7-11e9-9132-c1140e3f50ed.png)

Apologies if the issue is specific to Colab, but in general adding an item that biases the height of embedded Vega visualizations (if indeed that is what is happening here) seems like something we'd rather avoid.

**Comment by jheer** [comment]
On closer inspection, I see that the cut-off chart content (including axis title) exceeds the extra height of the actions menu, so the menu itself may not be the issue. Still, I'd be curious to know if vega-embed is doing anything that prevents accurate size determinations.

I don't see the issue when passing a Pandas table directly to Altair, such that Vega-Lite has a hard-wired values array. I do see the issue when loading data from an external URL. So the height issue may be due to asynchronous update issues.

**Comment by domoritz** [comment]
I don't thing Vega Embed fixes the size of any elements. Is the chart cut off because the canvas is too small or because the wrapping element is too small? 

I agree that the action menu should not move the chart.

**Comment by jheer** [comment]
Hmm, it might not be a vega-embed issue specifically then. The HTML canvas/svg is the right size. It is the parent container in Colab that is too small and so requires scrolling. It might be a Colab-specific issue as I have not tested on standard Jupyter notebooks. I think Colab may be sampling the web component size before the chart has fully loaded. Then the data loads and the container is too small. So, feel free to close if this is not something vega-embed specifically should be concerned with...

**Comment by domoritz** [comment]
I noticed some general sizing issues on observable that might be related to this so I'll keep it open until I had time to look into it. In the meantime, do you want to file an issue with colab or wait?

**Comment by jheer** [comment]
At least for Observable I think Vega 5 might help, assuming we use runAsync and the runtime awaits a Promise before checking the height

**Comment by domoritz** [comment]
>  assuming we use runAsync

About that. Can you take a look at #130?

**Comment by domoritz** [comment]
Trying embed in https://github.com/vega/vega-embed/blob/master/test-container.html, I don't see any issues. Let me know if you think this is a problem with Embed.
