### ISSUE TITLE
when `patch` is applied, Open in Vega Editor should POST the patched Vega spec and not the unpatched vega-lite spec

### ISSUE THREAD

**Issue by declann** [vega/vega-embed#1336]
example:

https://observablehq.com/@domoritz/rotating-earth

select Open in Vega Editor results in an error due to no patch:

![image](https://github.com/vega/vega-embed/assets/353214/857f54a3-1232-4b16-b474-405feb5802a0)

This might be a straightforward fix and if it is I could suggest something this week or next

**Comment by domoritz** [comment]
Good catch. We send the unmodified spec which doesn't have the patch in it. I think we should change that (which means we would change the mode from Vega-Lite to Vega if there is a patch).

**Comment by declann** [comment]
Awesome, thanks for the quick fix!
