### ISSUE TITLE
production build failed

### ISSUE THREAD

**Issue by bharatpatil21** [vega/vega-embed#1339]
build failed 

`./node_modules/react-vega/node_modules/**vega-embed/build/vega-embed.module.js** 1211:17
Module parse failed: Identifier directly after number (1211:17)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
|   const editor = window.open(url);
>   const wait = 10_000;
|   const step = 250;
|   const {`

Need to fix below  variable (wait) value 10_000

![image](https://github.com/user-attachments/assets/8065fa46-bc0c-4f5c-b2bd-12a5a5441807)

**Comment by domoritz** [comment]
Looks like you may have outdated libraries. There are not enough details to repro but please update all your tooling and see whether it fixes your build.

**Comment by bharatpatil21** [comment]
After update latest version(6.26.0) get same build error like below,

![image](https://github.com/user-attachments/assets/7708b0fc-93a0-43b4-ac46-d49cfc1803ec)
