### ISSUE TITLE
Release Candidate versions are included in dependency tree

### ISSUE THREAD

**Issue by rowles** [vega/vega-embed#135]
I noticed release candidate versions are included in vega-embed's [dependency graph](https://npm.anvaka.com/#/view/2d/vega-embed).

There have been a couple [situations](https://github.com/jupyterlab/jupyterlab/issues/6086) where JupyterLab's build process has broken due to bad RC versions.

**Comment by domoritz** [comment]
I'll release Vega-Embed 4 when Vega-Lite 3 and Vega 5 are final.
