### ISSUE TITLE
Pin deps to more specific compatible versions

### ISSUE THREAD

**Issue by tafsiri** [vega/vega-embed#136]
Hi, This is a request for a release on the 3.x branch that has more specific dependency ranges specified. In particular I believe this line https://github.com/vega/vega-embed/blob/v3.29.1/package.json#L72 has caused an issue for me. The range ^3.0.0-rc12 matches 3.0.0-rc14 (and subsequent rcs that will be released) and it appears there are breaking changes in those releases.

I noticed this because I have a project that was using vega-embed 3.28.0 (along with vega-lite 3.0.0-rc10). However recent installs/builds (using yarn) resolve vega-lite to 3.0.0-rc14 which isn't compatible and the project doesn't build. 

I'm partway through upgrading to the 4.x rc line which resolves this through peerdeps (though I ran into some issues there which i'm still working on), but it would be nice to have a version on the 3.x line that aligns with required dependencies.

**Comment by domoritz** [comment]
Vega-Embed should be compatible with any recent Vega and Vega-Lite version and so I prefer not to fix particular versions. However, since Vega-Lite 3 rc 14 now targets Vega 5 instead of Vega 4, I agree that we should limit the compatibility. I'll make a maintenance release that fixes to rc 12.

**Comment by domoritz** [comment]
Can you test 3.30?

**Comment by domoritz** [comment]
Out of curiosity, do you think that peer dependencies are the right way to move forward in Embed v4?

**Comment by tafsiri** [comment]
@domoritz thanks. 3.30.0 works for me.

To the bigger questions of peer deps going forward, as a library author (writing something on top of vega). I welcome it because it gives me greater control over the upgrade cycle of the underlying libraries. So I don't have to worry about something breaking outside of me specifically upgrading (or being looser with my dependencies and having test infrastructure to catch breakages). 

Its more work up front (I've had to spend a fair amount of time making sure I got compatible versions of the various dependencies), but results in a more reproducible experience.

One thing I think it would be helpful to make it less work is having some hints as to what works in the peerDependencies entry. As is https://github.com/vega/vega-embed/blob/master/package.json#L70 has `*` version specifier which I don't really trust as a reasonable range :). But I use what is in devDependencies as a clue to a stable setup. 

A bigger question I would have is whether other libs libs like vega-lite are going to use peerDeps. Basically given https://github.com/vega/vega-lite/blob/master/package.json and the devDependencies in vega-embed, would I ever end up in a situation where i have multiple copies of vega in my node_modules or bundle. I think resolving how to know what is compatible with what is the big underlying issue. Regular dependencies generally solve that, but IMO need stricter (more stable) ranges.

**Comment by domoritz** [comment]
Thank you for your insights. I will move forward with peer dependencies then. However, I don't think I want to specify compatible versions in Vega-Embed since Embed works with a range of compatible versions. Instead, I think we should make Vega a peer dependency of Vega-Lite and specify the compatible version range there. See https://github.com/vega/vega-lite/pull/4666 for a PR towards that.
