### ISSUE TITLE
Repeat results in: WARN Unknown repeated value "repeat"

### ISSUE THREAD

**Issue by epicyclist** [vega/vega-embed#137]
I've created an Observable example describing the issue [here](https://observablehq.com/@epicyclist/vegaembed-and-repeat). In short: using `repeat` in a spec results in a warning and an incorrect graph.

**Actual**
<img width="383" alt="Screen Shot 2019-03-14 at 11 55 07 AM" src="https://user-images.githubusercontent.com/802575/54383781-14b14280-4650-11e9-8d81-bbb1041a26d2.png">

**Expected**
<img width="1070" alt="Screen Shot 2019-03-14 at 11 45 00 AM" src="https://user-images.githubusercontent.com/802575/54383792-1a0e8d00-4650-11e9-8094-91dd9922ee23.png">

**Comment by epicyclist** [comment]
I may have found the issue. Both Observable and my project use vega-embed 3.30.0 which uses vega-lite 3.0.0-rc12. The Vega Lite Editor, however, does not use vega-embed and pulls in vega-lite 3.0.0-rc14.

Can the version of vega-lite be bumped to rc14 for this project?

**Comment by domoritz** [comment]
Rc 14 needs Vega 5. We'll make a release when Vega makes a release that fixes a critical bug.
