### ISSUE TITLE
Updates for vega 3

### ISSUE THREAD

**Issue by rgbkrk** [vega/vega-embed#15]
I went ahead and tested to see if our app was ready for vega 3 by trying out the beta. This package is using a path that doesn't exist any more, `require('vega').util.mutator` - `util` is no longer available.

**Comment by kanitw** [comment]
Vega-Embed will be deprecated in Vega 3, so you wouldn't need this package any more. :)

**Comment by kanitw** [comment]
@jheer Maybe we should write in the README so people know about this?

**Comment by rgbkrk** [comment]
Ah great, happy to switch!

**Comment by kanitw** [comment]
Actually, we might not deprecate it.  My colleagues are still looking into this.
