### ISSUE TITLE
[bug] vegaEmbed doesn't wait till the figure is fully embedded

### ISSUE THREAD

**Issue by alexeypetrushin** [vega/vega-embed#150]
**Problem:** `vegaEmbed('#vis', spec)` return promise, I suppose it should be resolved when all the rendering done and figure is fully embedded. But it's not how it's working it resolves earlier than it should.

**Details:** In my code I wait for `vegaEmbed` to finish and then scroll page to the embedded figure. And it's not working, scrolling has wrong position as if there was no any figure at all. What happens is (you can visually see that) the embedded figure flashes quickly at the top of the page and then jumps to the place it supposed to be. I suppose that `vegaEmbed` resolves earlier than it should be, it resolves probably at the time the figure is rendered and embedded but not placed where it should be placed in the page. And so - when I try to scroll - the wrong position is calculated because figure is not yet placed in place it should be. So - `vegaEmbed` does half the job and resolves, I do scrolling to wrong position, and then `vegaEmbed` does some other part and places the figure at the place it should be.

**Workaround:** I have workaround to wait 1ms after `vegaEmbed` resolves and then triggering the scrolling function `setTimeout(scrollFn, 1)` then it works as it should. I also tried to used forced Browser re-paint instead of delay, but it's not working.

**Comment by domoritz** [comment]
Odd. We wait for Vega to finish everything in https://github.com/vega/vega-embed/blob/739211e3c50cc4dc82fd363b52f9a2429d9acccb/src/embed.ts#L301 so I wonder whether this is a Vega-Embed issue or not. Note that browsers might wait for a rendering step (which you can wait for with https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame). Can you help clarify this?

**Comment by alexeypetrushin** [comment]
Thanks. Hmm, strange, maybe I have some bug in my code. 
I tried to wait for animation frame too but it's not working either. 
I try to create test case so it could be repeated. Closing issue for now, will reopen it when attach the test case.
