### ISSUE TITLE
"No default export" errors with vega-lite when run via angular

### ISSUE THREAD

**Issue by ogreyard** [vega/vega-embed#151]
Hello there, 

I am currently facing the following issue when trying to run from an angular app via vegaEmbed:

> ERROR in node_modules/vega-lite/build/src/util.d.ts(1,10): error TS2305: Module '
> "....../node_modules/@types/clone/index"' has no exported member 'default'.
> 
> node_modules/vega-lite/build/src/util.d.ts(2,8): error TS1192: Module '"...../node_modules/@types/fast-json-stable-stringify/index"' has no default export.
> 

I have the following versions installed via npm:

```
"vega": "~5.3.5",
"vega-lite": "3.2.1",
"vega-typings": "0.6.2",
"vega-embed": "~4.0.0"
```

Could you point me in the right direction for further investigation?

Thanks!

Kind regards
Markus

**Comment by domoritz** [comment]
This is a problem with the setup. You might need to enable synthetic imports.

**Comment by ogreyard** [comment]
> This is a problem with the setup. You might need to enable synthetic imports.

this is related: https://github.com/vega/vega-lite/issues/4461
