### ISSUE TITLE
Option to change horizontal placement of the ... button?

### ISSUE THREAD

**Issue by ralexx** [vega/vega-embed#155]
The button's placement on the right side of its host image is not ergonomic for my use case. I don't see an option for a calling application to set this attribute. Would it be feasible to add horizontal alignment as an option?

### Example
When I use [Altair](https://github.com/altair-viz/altair) in a Jupyter notebook to draw a chart whose dimensions are larger than the available screen space in my browser window, the vega-embed button is pushed off-screen. Jupyter anchors cell content to the top left corner of cells so I have to scroll (a lot, in my case) to reach it. If the button's horizontal alignment attribute was either accessible to end users or to the package developer whom I could then petition separately, it would address this use case.

**Comment by domoritz** [comment]
Thanks for raising the issue. Maybe we can modify the CSS to make the chart scroll but keep the actions button fixed at the top right. I think having a good default would be better than making placement configurable, don't you think?

**Comment by ralexx** [comment]
Scrolling is not a problem in Jupyter notebook (and presumably Jupyterlab): no change is needed there. It just happens that I have a series of charts that I need to export whose dimensions are exceed the Jupyter cell dimensions. This moves the button off-screen and forces me to scroll to reach it.

I do agree that a sane default is better than making placement configurable. Not knowing the rationale behind the button's placement, I did not want to assume that my relatively trivial issue was worth arguing for a different default. That said, I quite like the vega-embed button -- functionally and aesthetically -- and changing the horizontal positioning of the button would improve ergonomics for any application users who produce chart objects that scroll off the right edge of left-aligned UI windows.

**Comment by domoritz** [comment]
The default at the top right seemed reasonable. I think we should improve placement on both JupyterLab as well as Observable for wide charts. 

You can easily disable the default style btw.
