### ISSUE TITLE
ES6 arrow functions and string templates in built version of the NPM package.

### ISSUE THREAD

**Issue by Petro-Kashpurenko** [vega/vega-embed#163]
In the built version of vega-embed:
npm i vega-embed@4.2

the file vega-embed.js holds arrow functions and string templates, which breaks the IE

**Comment by domoritz** [comment]
Vega itself requires es6 as documented at https://vega.github.io/vega/usage/internet-explorer/. You can transpile with babel to get support for older browsers.
