### ISSUE TITLE
vega-embed with svelte? rollup question?

### ISSUE THREAD

**Issue by zahachtah** [vega/vega-embed#167]
Hi, I am trying to get vega-embed to work within svelte javascript framework (https://svelte.dev/). Svelte uses rollup but I seem to be doing something wrong. I define the following

```
	import * as vega from 'vega@5'
	import *  as vegaLite from 'vega-lite@3'
	import * as vegaEmbed from 'vega-embed@4'
```
but this does not work, neither vega, vegaLite nor vegaEmbed are defined.

and the compiler tells me: 

```
vega-lite@3 (imported by src/TestIt.svelte)
vega-embed@4 (imported by src/TestIt.svelte)
vega@5 (imported by src/TestIt.svelte)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
vega@5 (guessing 'vega')
```

I probably am doing something stupid.....

**Comment by domoritz** [comment]
That seems to be a question for https://github.com/vega/vega. Can you just set the output name to Vega to get rid of the warning?
