### ISSUE TITLE
Peer dependancies to help reduce errors like: Can't resolve 'd3-selection'

### ISSUE THREAD

**Issue by QuantumInformation** [vega/vega-embed#18]
Can there be some peer deps on things like d3 and other libs to make it more obvious to newcomers what libs we need? The error Can't resolve 'd3-selection' could be related to d3 versioning.

![image](https://cloud.githubusercontent.com/assets/216566/23019209/0dd67de2-f439-11e6-923b-04e60cb85263.png)

here is what I am trying to do:
https://github.com/quantumjs/atmospheric-diagnostics/blob/vega/src/AtmosphericDiagnostics.ts#L8

**Comment by domoritz** [comment]
Good catch! Let me know if the latest beta 1 fixes this for you.

**Comment by gnestor** [comment]
I'm still seeing this issue for 3.0.0beta5:

```
ERROR in ./~/vega-embed/src/embed.js
    Module not found: Error: Cannot resolve module 'd3-selection' in /Users/grant/Sites/jupyter/jupyterlab_vega/nbextension/node_modules/vega-embed/src
     @ ./~/vega-embed/src/embed.js 1:9-32
    
    ERROR in ./~/vega-embed/src/embed.js
    Module not found: Error: Cannot resolve module 'vega' in /Users/grant/Sites/jupyter/jupyterlab_vega/nbextension/node_modules/vega-embed/src
     @ ./~/vega-embed/src/embed.js 2:11-26
    
    ERROR in ./~/vega-embed/src/embed.js
    Module not found: Error: Cannot resolve module 'vega-lite' in /Users/grant/Sites/jupyter/jupyterlab_vega/nbextension/node_modules/vega-embed/src
     @ ./~/vega-embed/src/embed.js 3:9-29
    
    ERROR in ./~/vega-embed/src/embed.js
    Module not found: Error: Cannot resolve module 'vega-schema-url-parser' in /Users/grant/Sites/jupyter/jupyterlab_vega/nbextension/node_modules/vega-embed/src
     @ ./~/vega-embed/src/embed.js 6:19-52
```

I see that these dependencies are listed as normal dependecies in `package.json`, so I'm not sure what the issue is. I had the same issue with 2.2.0 and ended up just adding vega-embed's dependencies to my own project.

**Comment by domoritz** [comment]
Yeah, I reverted the change because it was causing issues because vega and vega lite are still in beta and alpha. Just add them as normal dependencies.

**Comment by domoritz** [comment]
Let me know if it was better if we made vega and vega-lite dev dependencies.
