### ISSUE TITLE
Vega embed broken

### ISSUE THREAD

**Issue by ragesoss** [vega/vega-embed#21]
It looks like a change in vega or vega-embed.js since yesterday are causing errors.

In particular, here's the error I'm seeing throughout my test suite, which appeared this morning:

```
        TypeError: undefined is not an object (evaluating '(typeof window !== "undefined" ? window['vg'] : typeof global !== "undefined" ? global['vg'] : null).util.mutator')
             at http://vega.github.io/vega-editor/vendor/vega-embed.js:181
             at http://vega.github.io/vega-editor/vendor/vega-embed.js:364
             at http://vega.github.io/vega-editor/vendor/vega-embed.js:1 in s
             at http://vega.github.io/vega-editor/vendor/vega-embed.js:1
             at http://vega.github.io/vega-editor/vendor/vega-embed.js:6
             at http://vega.github.io/vega-editor/vendor/vega-embed.js:176
             at http://vega.github.io/vega-editor/vendor/vega-embed.js:1 in s
             at http://vega.github.io/vega-editor/vendor/vega-embed.js:1 in e
             at http://vega.github.io/vega-editor/vendor/vega-embed.js:1
             at http://vega.github.io/vega-editor/vendor/vega-embed.js:1
```

I get an error about vg.embed not being a function when I try to view the vega graphs on my project.

**Comment by domoritz** [comment]
Can you use vega-embed from a CDN (https://cdnjs.com/libraries/vega-embed) and see whether you still get the error. 

Can you also make sure that you using vega embed 2 and vega 2?

**Comment by ragesoss** [comment]
Ah, great! Thanks. That fixed the problem.

I had followed the example here, pulling the resources from vega.github.io: https://github.com/vega/vega/wiki/Embed-Vega-Web-Components

**Comment by domoritz** [comment]
Hmm, this should still work but I'm glad this fixed the problem for you.

**Comment by ragesoss** [comment]
Here's the diff that fixed it: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/8493f88281bf0da38adaaa622f5092c9e4a4d568

The old version had been working until today.

**Comment by domoritz** [comment]
Ahh, I see. The problem was that `https://vega.github.io/vega/vega.js` now points to Vega 3. Sorry about that. 

cc @jheer
