### ISSUE TITLE
would `Save as PDF` be feasible ?

### ISSUE THREAD

**Issue by g3o2** [vega/vega-embed#213]
I've read in the [vega command line utils](https://vega.github.io/vega/usage/#cli) documentation about the function __vg2pdf__.

If this was feasible in vega-embed, this feature could be implemented as another export option.
Potentially impacted properties: `actions.export`, `scaleFactor`, `i18n`, `downloadFileName`.

**Comment by domoritz** [comment]
The PDF generation needs a server component. It currently doesn't work in the browser. See https://github.com/vega/editor/issues/158 for details. 

Would you be okay with me closing the issue here and move the discussion over to the other one?

**Comment by g3o2** [comment]
sure, thanks
