### ISSUE TITLE
scss causes differences in development and production webpack

### ISSUE THREAD

**Issue by melissachang** [vega/vega-embed#221]
I use Create React App which uses webpack. I'm seeing styling differences between webpack production and development modes.

Webpack production mode:

![1](https://user-images.githubusercontent.com/10929390/64737191-22ca0980-d4a1-11e9-98bd-26ede6911cb2.png)

Webpack development mode:

![2](https://user-images.githubusercontent.com/10929390/64737211-2a89ae00-d4a1-11e9-9f95-4518319017c4.png)

It turns out that in development mode, a div had `vega-embed` class with [these three styles](https://github.com/vega/vega-embed/blob/c226d81189e9c3387dd3cca1abb4da9cc80f18b5/vega-embed.scss#L2-L4):

![1](https://user-images.githubusercontent.com/10929390/64737290-560c9880-d4a1-11e9-9683-4789a04e0844.png)

Whereas the div didn't in development mode didn't have `vega-embed`:

![2](https://user-images.githubusercontent.com/10929390/64737305-5e64d380-d4a1-11e9-8b3b-ea513d410340.png)

It looks like I have to do something special to get `.scss` files working in development mode.

I believe this problem would go away if the `.scss` file was switched to a normal `.css` file.

**Comment by domoritz** [comment]
That's odd. https://github.com/vega/vega-embed/blob/master/build-style.sh builds a is file that has the css in it. I suspect that the issue isn't scss.

**Comment by melissachang** [comment]
Ok. Closing this issue as I don't exactly what is causing this. Hopefully someone will post a workaround/fix at some point. Thanks.

**Comment by domoritz** [comment]
I'm really surprised that the class is there in one case but not the other. Sounds like a webpack bug to me. Do you have a small example that shows the issue?

**Comment by melissachang** [comment]
I don't have a small example, but here's how you can repro.

- Webpack production mode: Just go to https://test-data-explorer.appspot.com
- Webpack development mode: Follow [these instructions](https://github.com/DataBiosphere/data-explorer#quickstart) (just first three steps)

**Comment by melissachang** [comment]
I'm not 100% sure Webpack production vs development mode is the culprit. There's no easy way to start a local webpack in production mode.

**Comment by domoritz** [comment]
Webpack does certain optimizations in production that could cause issues. You can quickly switch to production by changing the `mode` in your webpack config: https://webpack.js.org/configuration/mode/.

**Comment by melissachang** [comment]
I use [Create React App](https://github.com/facebook/create-react-app). This is a popular way to bootstrap a react app. I don't have a webpack config I can edit. Webpack config is in the [`react-scripts` package](https://github.com/facebook/create-react-app/tree/master/packages/react-scripts/config).

Basically anyone who uses Create React App will have this problem where the Vega chart is styled differently on localhost and in production.

**Comment by domoritz** [comment]
Sounds like a bug with CRA then. Can you file an issue with them?

**Comment by melissachang** [comment]
When I google for CSS differences betweeen development and production webpack modes, scss comes up ([example](https://github.com/facebook/create-react-app/issues/6368#issuecomment-461983100)).

I would have to [configure CRA to support SCSS](https://create-react-app.dev/docs/adding-a-sass-stylesheet). Perhaps that is why things aren't working for me -- because I haven't done this configuration.

It would be nice if we could use vega-embed without having to do this configuration. If vega-embed used .css instead of .scss, we wouldn't have to do this configuration. That's what this issue is about.

**Comment by domoritz** [comment]
I don't think scss is the problem. I compile to CSS before the JavaScript compiles. The problem seems to be the missing class.

**Comment by melissachang** [comment]
Could be. Unfortunately I don't have time right now to debug and figure out what exactly is going on.
