### ISSUE TITLE
Removing padding from '.vega-embed'

### ISSUE THREAD

**Issue by WhoAteDaCake** [vega/vega-embed#226]
Hello, I've noticed that `.vega-embed` class contains `padding-right: 38px;`, which can get in the way when displaying charts. Is there any way to remove it ?

For context, I am using `react-vega`

**Comment by domoritz** [comment]
We add this passing for the action button. We could remove it when there is no action button. Or do you have a different suggestion?

**Comment by WhoAteDaCake** [comment]
I would say removing when there is no action button would be the best. Thanks for your response

**Comment by domoritz** [comment]
Sounds good. Can you send a PR?

**Comment by WhoAteDaCake** [comment]
I've opened #228 . Could you take a look and let me know if it's ok?
