### ISSUE TITLE
"Open in editor" does not show the spec+plot when using firefox

### ISSUE THREAD

**Issue by johanneskoester** [vega/vega-embed#227]
Clicking "Open in editor" to see the plot and the spec only works with google chrome. In Firefox, you are taken to the editor, but it just shows your last view instead of updating to the corresponding plot and spec.

**Comment by domoritz** [comment]
Hmm, it actually works for me in FF 70.0b10. Can you make sure that you have popups enabled and that you don't prevent post messages?

**Comment by johanneskoester** [comment]
You are right, it suddenly works again. No idea what was wrong before. The popup was opened, but the editor did not update. Maybe a temporal glitch in the editor. Sorry for the noise!

**Comment by domoritz** [comment]
Thanks for the upate.
