### ISSUE TITLE
something in vega-embed changed and our graphs no longer work and i don't know what it is and it's kind of embarrassing

### ISSUE THREAD

**Issue by jowens** [vega/vega-embed#25]
You can see our embarrassment here:

http://gunrock.github.io/gunrock/doc/latest/md_stats_engines_topc.html

Firefox (for instance) says:

`TypeError: (intermediate value).util is undefined[Learn More]` (vega-embed.js 181)

which is the JS code

`    $ = (typeof window !== "undefined" ? window['vg'] : typeof global !== "undefined" ? global['vg'] : null).util.mutator;`

Our current includes are:

```
        <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
        <script src="http://vega.github.io/vega/vega.js" charset="utf-8"></script>
        <script src="http://vega.github.io/vega-lite/vega-lite.js" charset="utf-8"></script>
        <script src="http://vega.github.io/vega-editor/vendor/vega-embed.js" charset="utf-8"></script>
```

This used to work. I'd appreciate a pointer to how I might fix this. Is there some sort of mailing list or twitter account or web page where y'all announce deployed-code changes that might impact us? This is probably my fault somewhere down the chain, sorry to bug you here.

**Comment by arvind** [comment]
Sorry about that @jowens. We've "soft-launched" Vega 3, and inadvertently broke old URLs people were using. You can switch your imports to the following to get back to the Vega 2 stack:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vega/2.6.5/vega.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/1.3.1/vega-lite.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vega-embed/2.2.0/vega-embed.js" charset="utf-8"></script>
```

**Comment by jowens** [comment]
OK. Many thanks @arvind! Two questions then:
- Is there an upgrade path with Altair to Vega 3?
- Is there a place that announcements like this are made so when breaking changes happen, I can fix our stuff up?

**Comment by jheer** [comment]
For announcements, you can look at the vega-js google group:
https://groups.google.com/forum/#!forum/vega-js
