### ISSUE TITLE
Facets with columns not working

### ISSUE THREAD

**Issue by GitNoise** [vega/vega-embed#269]
I am trying to make a trellis/small multiple chart. 
The spec works in the official vega-lite editor (https://vega.github.io/editor/) but not when I use vega-embed.

I specified the faceting like so (see rest of the spec below the images):
```
 "facet": {
      "field": "Klubb",
      "type": "nominal",
      "columns": 5
    },
```

These are the scripts and versions of vega/vega-lite/vega-embed I use: 
```
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega/5.7.0/vega.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/3.4.0/vega-lite.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-embed/5.1.3/vega-embed.min.js"></script>
```
**In the vega editor i see this (working trellis):**

![Screenshot 2019-11-14 at 15 04 36](https://user-images.githubusercontent.com/2017520/68863572-eeb4d400-06ef-11ea-9d12-9da9e6ee0434.png)

**And using vega-embed I see this (all on one row):**

![Screenshot 2019-11-14 at 15 03 37](https://user-images.githubusercontent.com/2017520/68863542-de045e00-06ef-11ea-87df-04e6d6d36ab6.png)

**The json I use to generate the chart is this:**

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "url": "data.json"
  },
  "transform": [
	  {"filter":  {"field": "Position", "oneOf": ["Back", "Forward", "Målvakt"]}}
	  ],
  "mark": "bar",
  "encoding": {
	  "facet": {
      "field": "Klubb",
      "type": "nominal",
      "columns": 5
    },
    "x": {
      "bin": {"step": 100000 }, "field": "Inkomst i kr", "type": "quantitative",  "sort": "-y", "title": "Inkomst (kr)"
    },
    "y": {
      "aggregate": "count", "field": "*", "type": "quantitative", "title": null
    },
	"color": { "field": "Position", "type": "nominal"}
  }
}

```

Gist: https://gist.github.com/GitNoise/5169448c0094390a4b8a83fd4c635a0b

Running code: https://bl.ocks.org/GitNoise/5169448c0094390a4b8a83fd4c635a0b/f3dd8a608326da93f27e5aae35aa5dade8a25fd0

**Comment by domoritz** [comment]
Please upgrade to Vega-Lite 4 to get support for columns.
