### ISSUE TITLE
keep the top-level vega(-lite) config block in the (compiled) vega specification

### ISSUE THREAD

**Issue by g3o2** [vega/vega-embed#27]
With vega-embed, a top-level vega-lite config block currently disappears from the compiled vega spec and is passed on separately.

Given that the top-level config block takes precedence over external configurations anyway, there does not seem to be any benefit with the current behaviour. What's more, it _always_ removes the config block from `result.spec`, which is inconvenient in case that the specification is loaded from a `json` file.

Shouldn't the separate passing on be reserved to a configuration referenced via vega-embed's `config` parameter, i.e. for external configurations? Alternatively, it would be nice to provide yet another parameter to let the user decide how a top-level config block should be handled by vega-embed.

Also see the discussion here: https://github.com/vega/vega-lite/issues/2333

**Comment by domoritz** [comment]
Agreed. We need to write some code to strip all the Non-Vega config from the Vega-Lite spec and will then add it to the output.

**Comment by kanitw** [comment]
Fixed in https://github.com/vega/vega-lite/pull/2372
