### ISSUE TITLE
Enabling actions in vega embed causing sub menu's three dots to render on full screen

### ISSUE THREAD

**Issue by learnwithratnesh** [vega/vega-embed#271]
This is the issue i observed in latest version of vega embed

**Comment by domoritz** [comment]
I can't reproduce the issue in https://bl.ocks.org/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9. Can you explain what's going wrong?

**Comment by learnwithratnesh** [comment]
By setting 
` embed(bar, this.barData, { 'actions': true, 'renderer': 'svg' }).then((result: vegaEmbed.Result) => result.view);`

I am not able to upload screenshot 
Dependencies:
`"dependencies": {
    "vega": "^5.8.0",
    "vega-embed": "^6.1.0",
    "vega-lite": "^4.0.0-beta.11"
  }`

**Comment by domoritz** [comment]
Can you try to drag and drop a screenshot? Also, what browser and OS are you using? Do you have any custom CSS?

**Comment by learnwithratnesh** [comment]
https://github.com/learnwithratnesh/stencil this is my repo .It will hardly take 1-5 minutes for setup.

**Comment by domoritz** [comment]
Unfortunately, I don't have the cycles to look into your project. Could you try to reproduce the issue without any frameworks? Otherwise, I suspect that the issue is not in Vega-Embed.

**Comment by domoritz** [comment]
It looks like the issue is with the embedded style. Vega-Embed adds the style to the head but the framework seems to add `<br>` tags.

<img width="713" alt="Screen Shot 2020-01-07 at 18 42 32" src="https://user-images.githubusercontent.com/589034/71946051-7a416300-317d-11ea-8e86-0cc6f57897cf.png">
