### ISSUE TITLE
Webpack build with vega-embed as dependency fails without vega-lite installed too

### ISSUE THREAD

**Issue by jrajav** [vega/vega-embed#276]
vega-lite is only declared as a peer dependency of vega-embed, but a webpack build of a project depending on vega-embed will fail without vega-lite installed.

To reproduce, create a folder with this `package.json` inside:
```json
{
  "name": "repro",
  "version": "1.0.0",
  "main": "src/index.js",
  "scripts": {
    "build": "webpack"
  },
  "dependencies": {
    "vega": "^5.8.1",
    "vega-embed": "^6.1.0"
  },
  "devDependencies": {
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10"
  }
}
```

And this src/index.js:
```js
import "vega-embed";
```

Then run `npm install` and `npm run build` to see the error.

If vega-lite is added, the build succeeds:

```json
{
  "name": "repro",
  "version": "1.0.0",
  "main": "src/index.js",
  "scripts": {
    "build": "webpack"
  },
  "dependencies": {
    "vega": "^5.8.1",
    "vega-embed": "^6.1.0",
    "vega-lite": "^4.0.0-beta.12"
  },
  "devDependencies": {
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10"
  }
}
```

**Comment by domoritz** [comment]
Can you externalize Vega-Lite so that it's not included in the bundle? I'm doing this in rollup to create a Vega-Embed bundle without Vega-Lite. https://github.com/vega/vega-embed/blob/master/rollup.config.js#L18

**Comment by jrajav** [comment]
Yes, that actually does appear to be possible with webpack too, using its "externals" option (https://webpack.js.org/configuration/externals/). In our project, we did it something like this:

#### webpack.config.js
```js
module.exports = {
  ...
  externals: {
    "vega-lite": "{}"
  },
  ...
}
```

Thank you @domoritz !
