### ISSUE TITLE
Vega embed does not work with Content Security Policy in secure environments.

### ISSUE THREAD

**Issue by jornfranke** [vega/vega-embed#288]
If the Content Security Policy does not allow "unsafe-eval" then the vega-embed cannot be loaded as it depends on vega-util and vega-util uses in field.js an unsafe-eval operator ("Function"):
https://github.com/vega/vega-util/blob/master/src/field.js

See here for information about  Function https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function.

Despite that the problematic field.js is not used by vega-embed directly, it is automatically parsed by the browser when including vega-util as a NPM package. This leads to the case that the application is not executed by the browser anymore and thus vega-embed does not work in secure environments with restrictive content policies.

A potential solution could be to remove the dependency to vega-util (which is anyway archived) and replace the functions used from this library with own ones (all used functions are one-liners anyway).

**Comment by jornfranke** [comment]
duplicate to: https://github.com/vega/vega/issues/1106

**Comment by domoritz** [comment]
Vega util is an active dependency of Vega. Only the repo is archived because we moved to a monorepo.
