### ISSUE TITLE
embed.ts access directly window, preventing SSR

### ISSUE THREAD

**Issue by gillesdandrea** [vega/vega-embed#290]
See https://github.com/vega/vega-embed/blob/84a4febab5046927777ad6f5b2bd8fe782c0563b/src/embed.ts#L23

window variable is directly accessed, when code is embedded sever side, so I get the error `window is not defined`.

**Comment by domoritz** [comment]
Vega embed is not designed for node. When would this be a problem on the server side when the charts are eventually shown in a browser?

**Comment by gillesdandrea** [comment]
I’m using react-vega and I’m doing server side rendering. So client code is loaded in node and sometimes executed. That’s why it’s important in my case to always protect access to window variable that is not defined on server side.

**Comment by domoritz** [comment]
I see. How would we solve this issue then? Can you send a pull request?

**Comment by gillesdandrea** [comment]
@domoritz please check my proposal https://github.com/vega/vega-embed/pull/292

**Comment by gillesdandrea** [comment]
Hello @domoritz any chance to have a release including this fix soon?

**Comment by domoritz** [comment]
Yes, it's on my backlog after the holidays.

**Comment by domoritz** [comment]
Done
