### ISSUE TITLE
Async error not caught properly

### ISSUE THREAD

**Issue by alexeypetrushin** [vega/vega-embed#303]
Code contains an error, see `wrong_dates`, that won't be caught by `await vegaEmbed(...)`

vega-embed.js version 6.2.1

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "Stock prices of 5 Tech Companies over Time.",
  "data": {
    "values": [
      {
        "dates": ["2000-01", "2000-02", "2000-03"], 
        "gold": [1, 2, 1], 
        "silver": [1.5, 1, 2]
      }
    ]
  },
  "transform": [
    {"flatten": ["wrong_dates", "gold", "silver"]},
    {"fold": ["gold", "silver"], "as": ["symbol", "price"]},
    { "calculate": "datetime(datum.dates)", "as": "dates" }
  ],
  "mark": {"type": "line", "point": {"filled": false, "fill": "white"}},
  "encoding": {
    "x": {"field": "dates", "type": "temporal", "timeUnit": "yearmonth"},
    "y": {"field": "price", "type": "quantitative"},
    "color": {"field": "symbol", "type": "nominal"}
  }
}
```

[Playground](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAMp5u8ANZhC++DrDcAZmACsYACrIkYAMLcqIToSoxO3FS63oyoyHRqGpCa6HiYOKAQEJAU6GKsOthgANoaWWCZ5VnJqYU4xZAATAAMrSLNAIxqUC1tzY3dTa3N7QDMkAC6qmBlVZDU3GKaRcUd043THVMzVdWwjGJRKx107pvrE7MQAL6zlzfq2Xi6obAu3LqoK7PAkC5iqTwyBMJUgAHddMpqAB9FJA2CDBZLQb7Q7IXSTa6PLK-d7I+rzRbLaaQVFHbaQdAIgmwACeqHYi0G9kYjkx2IgwCg8Dy8FYAKBRRqQKMcQAFHDWKg6HCdABKQZUoWyhFgW4QKZJDC6axFX54WmEZBCiRKY0kwjcRhKPB6v4HMTIZY4Fx5WDIEkuB1CsGISSQa5YpLA+DcTTW6h62aQAAedq9yHxWlqCJJBqNQqBwQ+eUGouQAFUwrbTLTkOhPsoWAGOVBafHwknICy2WnDcbTABHVihIxpIxUGvR0NiD4NxPOqB0hlMtsZ0xKILW3PqtUga5AA)

**Comment by domoritz** [comment]
The editor doesn’t use embed. Is this an issue with embed or the editor?

**Comment by alexeypetrushin** [comment]
The issue is with the `vegaEmbed` or maybe with some `vega` internals.

**Comment by domoritz** [comment]
Thta's odd.

I'd expect this to catch any errors happening inside vegaEmbed but somehow it doesn't catch the stuff happening inside runAsync. 

```js
try {
          const result = await vegaEmbed("#vis", spec, {
            config: config,
            tooltip: { theme: "dark" }
          });

          console.log(result);
        } catch (error) {}
```

I don't have cycles to investigate this further. Can you take a look @alexeypetrushin?

**Comment by domoritz** [comment]
I can't reproduce the issue anymore. Errors are now caught properly for me if I test things with the example files in this repo.

**Comment by domoritz** [comment]
Oh, I can reproduce it with Vega-Lite.

**Comment by domoritz** [comment]
Ahh, the issue is that Vega uses `console.error` instead of throwing an error. Vega-Embed is correct.

**Comment by alexeypetrushin** [comment]
Shall we create the issue in Vega Repository and link it here maybe?

**Comment by domoritz** [comment]
Go ahead.

**Comment by alexeypetrushin** [comment]
From discussion on the issue in Vega - seems like it's the correct behaviour and the custom logger should be used to catch this error. 

> I think one can reasonably argue that this is correct behavior in Vega. You can override the logger (https://github.com/vega/vega/tree/master/packages/vega-util#logger) to handle errors yourself.

P.S. I personally think making error handling consistent - would be better way as it is now -sometimes errors are thrown and sometimes are not, but I'm fine with the workaround.

**Comment by domoritz** [comment]
I agree that we should try to be consistent! Maybe we can catch errors and convert them to log.error.
