### ISSUE TITLE
Bug `vega-embed` not working if schema URL format is changed

### ISSUE THREAD

**Issue by alexeypetrushin** [vega/vega-embed#305]
I found code below in vega-embed.js downloaded at https://www.jsdelivr.com/package/npm/vega-embed?path=build

It expect that the Vega Scheme URL to follow some arbitrary format, and if you change it it will blow up with `Uncaught TypeError: Cannot read property 'slice' of null`

```
/**
     * Parse a vega schema url into library and version.
     */
    function default_1(url) {
        var regex = /\/schema\/([\w-]+)\/([\w\.\-]+)\.json$/g;
        var _a = regex.exec(url).slice(1, 3), library = _a[0], version = _a[1];
        return { library: library, version: version };
    }
```

**Comment by domoritz** [comment]
We expect the schema to be a url pointing to https://github.com/vega/schema

**Comment by alexeypetrushin** [comment]
It won't work without internet.

**Comment by domoritz** [comment]
What is “it”?

Yes, the schema won’t resolve correctly anymore if github ever changes its hosting but I don’t expect that happening anytime soon. I don’t think there is a more stable URL that I could reasonably create but I’m open to suggestions.

Regardless of whether the URL resolves or not, we can parse it to get the version and mode until the end of time.

**Comment by alexeypetrushin** [comment]
I assumed that if vega-embed won't be able to fetch the schema (no internet or hosting change) it will break - and thus html page created with it will stop working. 

From your comment it seems like vega continue to work even if it wont' be able to fetch the schema. I guess in such case the issue is not important. 

Although this behaviour and relying on specific URL naming conventions is very unintuitive.
