### ISSUE TITLE
Is there an option to set browser caching to False?

### ISSUE THREAD

**Issue by todpole3** [vega/vega-embed#314]
Vega-embed is awesome, but I noticed that if we give it the path to a JSON, by default it will use the cached JSON file even if the JSON content has changed.

I wonder if there is a way to turn browser caching off, just like in $.ajax() you can prevent caching by setting a boolean parameter.

**Comment by domoritz** [comment]
As far as I know, caching depends on the browser and response codes from the server. But we should certainly be able to disable caching from the js side. For now, you can pass a custom vega loader to Vega-Embed and implement your own behavior. 

Would you mind reporting your results back here so others can benefit from what you've found?
