### ISSUE TITLE
"Open in Vega Editor" shows a compiled version

### ISSUE THREAD

**Issue by jazzido** [vega/vega-embed#35]
Hey,

Just noticed that when using `vega-embed` for displaying a Vega Lite chart, the "Open in Vega Editor" action opens the compiled Vega instead of the original Vega Lite. This behavior is also present in the documentation examples, e.g.: https://vega.github.io/vega-lite/docs/size.html#total-width-and-height-of-a-trellis-plots

**Comment by domoritz** [comment]
Yes, it would be better to show the Vega-Lite source. Would you be able to send a pr @jazzido?

**Comment by domoritz** [comment]
@sorenmacbeth noticed that this is a regression.

**Comment by domoritz** [comment]
Fixed in Beta 18.
