### ISSUE TITLE
Interactive Legend is not working

### ISSUE THREAD

**Issue by arraydude** [vega/vega-embed#351]
[Interactive legends](https://vega.github.io/vega-lite/examples/interactive_legend.html) are not working with vega-embed 6.0.0.

The graph is being generated but when I click on the legend it is not being highlighted.

I've tried this same _example spec_ [here](https://vega.github.io/editor/#/url/vega-lite/N4KAkARAxg9gdgMwJYHMIC4AEoyQG5ICmA7htuLtPAC5JwCuM9AzgOpIAm1AFmQCwAGAQBoKkWHFoMmzABKFU3amQDMQigF9wG0ZA4BDavrI5I9AE4AbMhCXUADs3QB6Z3kIp9AOhRIe9ACMvJBg3D30AWgMjZkJqZmdo-Wd6OEIAW3tLGABPdMJJCP0ocxhmZgi6DhZqcyJmLwArZngIbV0IdP1zAGsbbsJjDoLYDjo0LFMqbPMTMQhqHPtCGzgYdLp9a11KZEJLDhtYusJmCB3IZigtlcmxS6huDNvMaEMPGHMcgCYBALbcGAtLgdBQIDB7MU-Dk5oCqHAxrRWndAfgtvQXgBGC6XfaEKBIuBHPEEz4CTEATgBIIuEDw6JeAi8300OwgAA9YZRFssbNQMvZPltzvN9OykGcUXCOOt9HQyAgtrEcRAEJ8usosBAAKQATRFqIWSCgPQAykgAF6MsSguF7A42aIrWm0fIAVTgfhsOUG5nSNF4rLBMKlkB5LwgAEd6PpJH5DEh3AbKPoUChzOF+Ud6Olk5AxRKyAxLJZafbDlrYKllLTmEYTTYoAV+bNNO1wBBYpZ8YSuZ2SdQyZSuWGlhH0vRLLQ86qiAdJZgANr9k5nAC6tICVRs3ZQBUObaBHQAJFcnl0bHZHC4wp4fH5uIFgqEzxlku5PBFLH5CG4+F4mW+JoWiJDp9HoQdmEtF4pnDGxkBrMEJCMOgFwgSEODGOA0HbSAMKwiZyEoAIYGoQdcywX5tBADQgA) and it works correctly

_Example spec:_

```javascript
{
	"config": {
		"view": {
			"continuousWidth": 400,
			"continuousHeight": 300
		}
	},
	"data": {
		"url": "https://vega.github.io/vega-datasets/data/unemployment-across-industries.json"
	},
	"mark": "area",
	"encoding": {
		"color": {
			"type": "nominal",
			"field": "series",
			"scale": {
				"scheme": "category20b"
			}
		},
		"opacity": {
			"condition": {
				"value": 1,
				"selection": "selector019"
			},
			"value": 0.2
		},
		"x": {
			"type": "temporal",
			"axis": {
				"domain": false,
				"format": "%Y",
				"tickSize": 0
			},
			"field": "date",
			"timeUnit": "yearmonth"
		},
		"y": {
			"type": "quantitative",
			"aggregate": "sum",
			"axis": null,
			"field": "count",
			"stack": "center"
		}
	},
	"selection": {
		"selector019": {
			"type": "multi",
			"fields": ["series"],
			"bind": "legend"
		}
	},
	"$schema": "https://vega.github.io/schema/vega-lite/v4.0.2.json",
	"autosize": {
		"type": "fit",
		"contains": "padding"
	},
	"padding": {
		"bottom": 20
	}
}
```

**Comment by domoritz** [comment]
Please file this issue against Vega-Lite and specify which version you are using.
