### ISSUE TITLE
WebGL Renderer for Vega-embed

### ISSUE THREAD

**Issue by jerinjjose** [vega/vega-embed#361]
I want to render my vega-lite Graph using webgl renderer type. Currently I have seen there is only 2 options support by the vega-embed (svg,canvas).
https://github.com/vega/vega-webgl-renderer I want to use this package and render it within vega-embed.
I am using Angular 8 to render the vega-lite chart.
Following is my vega-embed options.

const embedOptions: EmbedOptions = {
    mode: 'vega-lite',
    theme: 'vox',
    defaultStyle: true,
    renderer: 'canvas',
    actions: false
}

I want to add webgl as a renderer option. Need to add this kind of option using vega-embed 
https://vega.github.io/vega-webgl-renderer/

**Comment by domoritz** [comment]
You can add the renderer to vega. It will work with Vega embed automatically.
