### ISSUE TITLE
have `opt.config` allow an URL to load the config object from a file

### ISSUE THREAD

**Issue by g3o2** [vega/vega-embed#37]
For now, only the visualisation specification can be optionally loaded from a file using `vega.embed`, while `opt.config` is to be provided as an object, not as an URL.

**Comment by domoritz** [comment]
I don't see this as a common use case and won't add it but we are happy to review a PR.

**Comment by arvind** [comment]
This functionality was supported in v2 of vega-embed, and I _think_ [is still supported](https://github.com/vega/vega-embed/blob/master/src/embed.js#L71)? Perhaps this is just a case of updating the documentation. @g3o2: Have you tried supplying a string as the `opt.config`?

**Comment by domoritz** [comment]
Yeah, looks like it is implemented. Please reopen if it's not working.

**Comment by g3o2** [comment]
Thank you @arvind and @domoritz, I can confirm that it works. So it is just a matter of updating the documentation.

**Comment by domoritz** [comment]
@g3o2 Excellent. Could you send a PR?

**Comment by g3o2** [comment]
@domoritz is this okay for you ? That's my first PR ever on Github ...

**Comment by domoritz** [comment]
@g3o2 Congratulations to your first merged pull request then. 🎉 

We love to get pull requests for documentation improvements.
