### ISSUE TITLE
SCRIPT1028 javascript error in Edge

### ISSUE THREAD

**Issue by flevobi** [vega/vega-embed#401]
Using vega-lite with vega-embed in Edge results in SCRIPT1028 javascript error which prevents rendering the visualisation. This can be checked using the following url: https://vega.github.io/vega-lite/demo.html that uses the following versions:

     <script src="https://cdn.jsdelivr.net/npm/vega@5.10.1"></script>
     <script src="https://cdn.jsdelivr.net/npm/vega-lite@4.10.4"></script>
     <script src="https://cdn.jsdelivr.net/npm/vega-embed@6.5.2"></script> 

The issue seems to be version-related because I have tried an older version and that didn't have the problem. These following combination of versions did work for me:

     <script src="https://cdn.jsdelivr.net/npm/vega@4"></script>
     <script src="https://cdn.jsdelivr.net/npm/vega-lite@3"></script>
     <script src="https://cdn.jsdelivr.net/npm/vega-embed@3"></script

Attached is a screenshot showing the issue
![vega-embed-error-in-edge png](https://user-images.githubusercontent.com/63649019/79305762-44d2b100-7ef4-11ea-9cbd-d14f0570c0d5.jpg)

**Comment by domoritz** [comment]
The issue is that ie does not support es6. I just added an es5 bundle you can use: https://github.com/vega/vega-embed/commit/2f5f5a46d9ce83b5bf77fdc31cbec6dd210be0d6 (note that you also need to use the es5 bundles for Vega and Vega-Lite.
