### ISSUE TITLE
Error: 'window' is not defined

### ISSUE THREAD

**Issue by tutmoses** [vega/vega-embed#403]
I get this error running vega 

> 'window' is not defined
> node_modules/vega-embed/build/vega-embed.js"

The culprit is on line 3874 in my installation and begins the section on backwards compatibility with Vega-Lite before v4:

`const w = window;`

**Comment by domoritz** [comment]
What browser are you using? Which versions? What’s the setup?

**Comment by tutmoses** [comment]
Ah yes, sorry I'm fairly new to this...

I'm running the Nuxt 2.12.2 and importing tfjs and tfjs-vis in the package.json. Vega is a dependency of tfjs-vis I think. My browser is Brave  1.7.92.

I've found I can fix the error by simply commenting out that line but of course it reoccurs if I ever need to delete the node_modules folder to upgrade anything.

Let me know if there's anything else you need.

**Comment by domoritz** [comment]
I have not heard of Nuxt and suspect this is an issue with the framework or the specific environment. In a browser, `window` should always be defined. Can you try to boil down the issue to a minimal reproducible example? As it stands, I don't think I can do anything.

**Comment by tutmoses** [comment]
You're right: Nuxt is a framework of Vue.js and there is related issue: https://github.com/nuxt/nuxt.js/issues/30. 

Is it not possible to define 'window'?
