### ISSUE TITLE
Consider listening for click rather than mousedown for viewSourceLink

### ISSUE THREAD

**Issue by miketaylr** [vega/vega-embed#420]
At https://github.com/vega/vega-embed/blob/ed326f48996dbb3c3fb8f0a4517f0523afa123be/src/embed.ts#L396 you're listening for `mousedown`, which triggers Firefox's popup blocker. 

These are the events that Firefox will allow to open a new window w/o user intervention:

`change click dblclick auxclick mouseup pointerup notificationclick reset submit touchend contextmenu`

So it might result in a nicer UX to change to `click` so Firefox users don't have to allow popups.

**Comment by miketaylr** [comment]
(just looking, and I guess it's more than just `viewSourceLink` that listen to `mousedown`, so it's probably worth changing them all, unless there's a specific usecase for mousedown?

**Comment by domoritz** [comment]
Good catch. Do you want to send a pull request to fix this?
