### ISSUE TITLE
vega-tooltip not working with vega-embed.3.0.0-beta.19 ?

### ISSUE THREAD

**Issue by g3o2** [vega/vega-embed#43]
When including vega-tooltip in the callback function of vega.embed(), everything works as expected with vega-embed.3.0.0-beta.18 but nothing happens with beta.19, et ceteris paribus.

**Comment by domoritz** [comment]
@g3o2 Vega-Embed 19 uses promises. See https://github.com/vega/vega-embed#embed.

you have to write 

```ts
embed(spec).then(function(view) {
    // use view to set up tooltips
})
```

**Comment by g3o2** [comment]
Oh, I see, not quite a subtle change ... Thank you!
