### ISSUE TITLE
Embed unable to properly show Trellis Plot when data is loaded and updated using the Vega view API

### ISSUE THREAD

**Issue by Thereatra** [vega/vega-embed#455]
I have been trying to combine the [Trellis Area](https://vega.github.io/vega-lite/examples/trellis_area.html) Vega Lite example and a [named data source](https://vega.github.io/vega-lite/docs/data.html#named) using the Vega view API to load the data at runtime and update the chart.

For testing purposes I have saved a small data sample in a variable which I then try to load in, resulting in the Trellis plot looking like the image below.
![image](https://user-images.githubusercontent.com/23458968/83086097-19fc8080-a08e-11ea-96d6-2ac6a1608267.png)
However if I use a values data field instead and copy paste the values directly into the Vega-Lite specification then it renders the plot correctly, as seen below.
![image](https://user-images.githubusercontent.com/23458968/83086137-34cef500-a08e-11ea-89b3-fc2bb837cfe0.png)

I have tried using the exact same Vega view API insert function setup with a single plot using multiple lines instead, which also renders correctly. Weirdly changing the minExtent on the x axis shows more of the plot?

I'm using the latest versions from jsdelivr
```
<script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@4"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
```

**Comment by domoritz** [comment]
Can you provide full working code? Also, make sure that you parse the data correctly.

**Comment by Thereatra** [comment]
So I spent quite a lot of time with this issue before posting issue and happened to solve it just 20 minutes after posting. I has somehow managed to miss the `autosize` property in the [specification](https://vega.github.io/vega-lite/docs/size.html#autosize) so the following settings solved it
```
"autosize": {
    "type": "fit",
    "contains": "padding"
}
```
I somehow also managed to miss the `view.resize()` function of the full [Vega view API](https://vega.github.io/vega/docs/api/view/#view_resize) which also solved the problem.

However in case the embed is suppose to automatically resize in this case without using the methods above, here is the html file I used for testing: https://gist.github.com/Thereatra/9077c47bb5733d212cc54e9fc96a1ac7

**Comment by domoritz** [comment]
Ahh, cool. Resizing is somewhat expensive so we don’t do it automatically. You as a developer know best when it’s necessary. I’m glad you found a solution.
