### ISSUE TITLE
Tooltip no longer works with more recent version s of vega-embed

### ISSUE THREAD

**Issue by owendall** [vega/vega-embed#46]
```javascript  

<script src="https://cdnjs.cloudflare.com/ajax/libs/vega/3.0.2/vega.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/2.0.0-beta.19/vega-lite.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-embed/3.0.0-beta.14/vega-embed.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/vega-tooltip/0.4.3/vega-tooltip.min.css"></link>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-tooltip/0.4.3/vega-tooltip.min.js"></script>
```
It is very confusing to try to debug which combination of the modules works.   I found that when I changed to vega-emebd/3.0.0-beta.20  my tooltips no longer showed up.  Do you have the same issue?

**Comment by domoritz** [comment]
Do you see any errors in the js console?

**Comment by owendall** [comment]
No, don't remember any.  But I will try again.

**Comment by owendall** [comment]
I just posted a gist for you to look at:

https://bl.ocks.org/owendall/69812eae7f6db0817aee8b610337f718

**Comment by domoritz** [comment]
I just updated https://vega.github.io/vega-tooltip/vega-lite-examples.html to the latest versions and everything works fine.

**Comment by domoritz** [comment]
Ahh, I see the issue. We changed embed to use a promise based API. Instead of passing a callback, you say `embed(...).then(...).catch(...)`. See https://github.com/vega/vega-embed#basic-example

**Comment by owendall** [comment]
Ah!  Now I get it.

**Comment by owendall** [comment]
Is that also true for tooltip?

**Comment by domoritz** [comment]
The tooltip doesn't have a callback.
