### ISSUE TITLE
Documentation for using Vega-Interpreter/AST/CSP with vega-embed for Single Page Applications (Angular etc.)

### ISSUE THREAD

**Issue by jornfranke** [vega/vega-embed#473]
I spend some time to get vega-embed work with vega-interpreter to ensure safe Content-Security-Policies (CSP). The issue was that vega-interpreter works with vega-embed using a Javascript only application. However, single page applications based on Angular (or any other framework) compile each module individually, which means one cannot share objectnames/variables cross modules. However, given the examples of the documentation this breaks the underlying assumption that they can be shared.

I did in the end a minor modification to make this also work.
The tested library versions are:
Angular 9 (older might work as well)
vega-embed 6.9.0
vega-interpreter 1.0.1

```

import {vega} from 'vega-embed';
import embed, {Mode,VisualizationSpec} from 'vega-embed';
import { Renderers } from 'vega';
import * as vegaInterpreter  from 'vega-interpreter';
 
{....}

 embedOpts={}
    embedOpts.ast=true;    
   
// this is the important line to add in single page applications
(vega as any).expressionInterpreter=vegaInterpreter.expressionInterpreter;
/// as usual 
       await embed(element, spec, embedOpts);
    

```

I propose to add this to the documentation. I verified that it works.

Please let me know if this is of interests.

**Comment by domoritz** [comment]
I'll do https://github.com/vega/vega-embed/issues/474 instead. It's cleaner and doesn't require any special documentation.

**Comment by jornfranke** [comment]
Both are needed according to the documentation.

**Comment by domoritz** [comment]
Yes, in Vega but Vega-Embed can be smart about it. I decided to implement a set of smart defaults.

**Comment by jornfranke** [comment]
Ok Great thanks a lot for your quick feedback and the Great work that you and the Vega Team do

**Comment by domoritz** [comment]
Thank you for being persistent, trying out fixes, and helping us get to cleaner solution.
