### ISSUE TITLE
Vega Embed does not work with ShadowDOM

### ISSUE THREAD

**Issue by doug** [vega/vega-embed#477]
The drop down for tooltip and hover don't behave if the embed is inside a shadowdom. 

Example: https://jsfiddle.net/chztgrsj/

**Comment by domoritz** [comment]
Probably because we are adding styles in a somewhat hacky way in https://github.com/vega/vega-embed/blob/master/src/embed.ts#L251. I don't have cycles to look at this soon. Do you want to take a stab at a fix?

**Comment by doug** [comment]
Yea looks like hacky styles is the source of the issue will take a look.

**Comment by doug** [comment]
This fixes it: https://github.com/vega/vega-embed/pull/498

**Comment by domoritz** [comment]
Fixed in 1185c77
