### ISSUE TITLE
Get from vgSpec axes range and domain

### ISSUE THREAD

**Issue by doomsayer2** [vega/vega-embed#480]
Greetings,

I would like to do some fancy additions to a rendered vega-lite chart. For the beginning I would want to start with listing some properties below the chart like the axis ranges min and max and so on. I will need them later on but it seems I can't find them or get access to them in a more generalized way. I could use the `data` to caluclate the `min` and `max` myself but I would like to read it from a generated vega chart no matter which one it is and not depend on specfic data sets and **key-value pairs**.

I have seen the `vgSpec` has a property called `scales` and this one is an array of the scales of the chart. Each scale is it's own object and has properties `domain` and `range` but they are not that what one would expect. So my question is if it is possible to get out the **range** of a compiled vega code.

Example: [https://jsfiddle.net/doomsayer2/0kfmcp6g/14/](https://jsfiddle.net/doomsayer2/0kfmcp6g/14/)

Thank you!

**Comment by domoritz** [comment]
You can access the scale properties at runtime through the Vega view api documented at https://vega.github.io/vega/docs/api/view/#data-and-scales.
