### ISSUE TITLE
Embed broken in Microsoft Edge (Regression in 6.10)

### ISSUE THREAD

**Issue by davidwales** [vega/vega-embed#517]
## Problem

Vega-embed 6.10 does not embed charts in Microsoft Edge.
Reverting to Vega-embed 6.9.2 works.

With Edge's exception behaviour set to break on exceptions, the following exception is raised:

```ShadowRoot is not defined```

This is linked to the following line of code:

```
return r instanceof ShadowRoot?{root:r,rootContainer:r}:{root:document,rootContainer:null!==(t=document.head)&&void 0!==t?t:document.body}
```

## Versions

- Vega: 5.13
- Vega-Lite: 4.14.1
- Vega-Embed: 6.10
- MS Edge: 44.18362.449.0
- MS Edge HTML: 18.18363
- OS: Windows 10, 1909

## Example Code

**EDIT:**

A quick and easy way to see this issue is to open the [Hello Vega-Embed](
https://observablehq.com/@vega/hello-vega-embed) Observable notebook in Edge. You will notice that the embeds don't work, and an error is raised. Simply editing the first code block to specify `"vega-embed@6.9.2"` immediately resolves the issue, and all the charts appear.

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>Vega-Lite Bar Chart</title>
    <meta charset="utf-8" />

    <script src="https://cdn.jsdelivr.net/npm/vega@5.13"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-lite@4.14.1"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-embed@6.10"></script>
    <!-- Simply changing the vega-embed version to '6.9.2' fixes the issue. -->

    <style media="screen">
      /* Add space between Vega-Embed links  */
      .vega-actions a {
        margin-right: 5px;
      }
    </style>
  </head>
  <body>
    <h1>Template for Embedding Vega-Lite Visualization</h1>
    <!-- Container for the visualization -->
    <div id="vis"></div>

    <script>
      // Assign the specification to a local variable vlSpec.
      var vlSpec = {
        $schema: 'https://vega.github.io/schema/vega-lite/v4.json',
        data: {
          values: [
            {a: 'C', b: 2},
            {a: 'C', b: 7},
            {a: 'C', b: 4},
            {a: 'D', b: 1},
            {a: 'D', b: 2},
            {a: 'D', b: 6},
            {a: 'E', b: 8},
            {a: 'E', b: 4},
            {a: 'E', b: 7}
          ]
        },
        mark: 'bar',
        encoding: {
          y: {field: 'a', type: 'nominal'},
          x: {
            aggregate: 'average',
            field: 'b',
            type: 'quantitative',
            axis: {
              title: 'Average of b'
            }
          }
        }
      };

      // Embed the visualization in the container with id `vis`
      vegaEmbed('#vis', vlSpec);
    </script>
  </body>
</html>
```

**Comment by domoritz** [comment]
Ups, we should add a check whether shadowroot is defined. Do you want to send a pull request?

**Comment by davidwales** [comment]
@domoritz Unfortunately I'm not a regular JavaScript user, so I'm not confident I know the best way to do that. Also, my workplace has not clarified whether I'm allowed to contribute code to open source projects during work hours. 😢 (I've put in a request to get permission/clarification, but it hasn't come back yet.)

**Comment by domoritz** [comment]
Okay. Thanks for filing the detailed issue. I'll look into it.

**Comment by domoritz** [comment]
Btw, not a problem on Edge 84.0.522.49. Can you update edge? 

I'm worried that even if I fix this particular issue, some other thing we use won't be supported by Edge. I have no good way to test this.

**Comment by domoritz** [comment]
Since this is not a problem in the latest Edge, please update your browser or use the previous Version of Vega-Embed.

**Comment by domoritz** [comment]
Please let me know if that's not an acceptable solution for you.

**Comment by davidwales** [comment]
I'll need to use the previous version of Vega-Embed. From what I can tell, Shadow DOM is only supported in the new Chromium version of Edge (released January 2020), which hasn't filtered through to my organisation's computers yet.

**Comment by domoritz** [comment]
I hope that's okay. You are only missing out on the shadow root feature, which would not be supported anyway and is only rarely needed.

**Comment by davidwales** [comment]
Yep, it's OK. Thanks for your support, and for Vega-Embed!
