### ISSUE TITLE
vega-embed version 3.0.0-rc`x` not on cdnjs

### ISSUE THREAD

**Issue by g3o2** [vega/vega-embed#52]
[https://cdnjs.com/libraries/vega-embed/](https://cdnjs.com/libraries/vega-embed/)

**Comment by domoritz** [comment]
Fixed in https://github.com/cdnjs/cdnjs/pull/12036.

**Comment by domoritz** [comment]
Fixed.

**Comment by curran** [comment]
FWIW It's on unpkg https://unpkg.com/vega-embed@3.0.0-rc7/build/vega-embed.min.js
