### ISSUE TITLE
rc questions / issues

### ISSUE THREAD

**Issue by chadbr** [vega/vega-embed#53]
last week I had a setup that looked like this (Angular2 / typescript if it helps):

I copied the vega-embed.d.ts form vega-lite and used it directly:

```
declare module 'vega-embed' {
  export const config: any;
  export default function embed(e: any, spec: any, ops: any): Promise<any>;
  export const vega: any;
}
```

Then I used it in a component like so: 

```
import embed from 'vega-embed';
import * as vega from 'vega';

...

  ngOnInit() {
    embed(this.chart.nativeElement, this.spec, { 'actions': false });
  }
```

with the RC, I removed my vega-embed.d.ts

The 1st problem I ran into I had to include vega-lite in my app or it would fail to compile with a 'vega-lite not defined' -- should it be required?

I added vega-lite, and now I can't get the embed function to compile:

```
import * as embed from 'vega-embed';
import * as vega from 'vega';
```

When I try to build -- I get these failures:

```
ERROR in /Users/chadbr/dev/vsts/kinetix-ui/node_modules/vega-embed/build/embed.d.ts (11,19): Namespace 'vg' has no exported member 'Loader'.

ERROR in /Users/chadbr/dev/vsts/kinetix-ui/src/app/simulation/result/result-chart/result-chart.component.ts (118,5): Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/Users/chadbr/dev/vsts/kinetix-ui/node_modules/vega-embed/build/embed"' has no compatible call signatures.
webpack: Failed to compile.

```

I've tried a few variations of this -- but clearly I'm missing something simple?

Thanks - Chad

**Comment by domoritz** [comment]
Hi Chad, thanks for taking the time to write this up. 

About your first issue. Vega-Lite is not required as you can use Vega-Embed with just Vega. This is why it's not a strict dependency and you can just ignore the peer dependency warning. Correct me if I'm wrong here. 

The build failures look like you have outdated Vega typings. Not sure where you got them from but you have a few options here. 

1. Copy the Vega typings from Vega-Lite
2. Import Vega typings from Vega-Embed (as we did in https://github.com/jupyterlab/jupyter-renderers/pull/15/commits/912fdacb9ee4e7679d262c2c45ef1276ac6d0a68#diff-e2ea9aaf0bf0bbdea9f9e0eb50e80a37R16)
3. Remove Vega typings and disable `noImplictAny` and wait for proper Vega typings. 

@kanitw, @arvind, @jheer and I have to talk about how we can get the complete Vega typings into the main repo to avoid these kinds of issues.

**Comment by chadbr** [comment]
Hello - 

So on the 'vega-lite' is required thing:

this is the error I get when I just upgrade vega-embed without changing any code:

```
$ ng build
Hash: a9e6089014ef159cbc7a
Time: 33503ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 240 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 755 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 1.75 MB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 11.7 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in ./~/vega-embed/build/embed.js
Module not found: Error: Can't resolve 'vega-lite' in '/Users/chadbr/dev/vsts/kinetix-ui/node_modules/vega-embed/build'
 @ ./~/vega-embed/build/embed.js 6:9-29
 @ ./src/app/simulation/result/result-chart/result-chart.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
error Command failed with exit code
```

If I change to the imports like so: 
```
import vegaEmbed from 'vega-embed';
```

I still get the error... if I install vega-lite, it clears the error.

---
I'm using the ```@types/vega``` typings because it's far more complete and I'm looking for the type checks on schema, etc.

I've added your loader definitions from vega-lite to the copy of ```@types/vega``` I have locally (with a few mods like this)

all seems well after that with the exception of needing to have vega-lite as noted above.

I'm sure I could quickly create a small angular app that repo's this if it helps?

**Comment by domoritz** [comment]
Hmm, yeah, I see the issue now. The problem is that the module loader expects all imports to resolve properly. Do you have an idea how I can make this work in Vega-Embed? Maybe we have to make Vega-Lite a strict dependency for everybody who creates bundles. cc @jheer

**Comment by chadbr** [comment]
maybe there needs to be a vega-embed and a vega-lite-embed that calls into vega-embed (I know... boooo)

**Comment by domoritz** [comment]
At that point I'd rather make Vega-Lite a strict dependency.

**Comment by domoritz** [comment]
Okay, I made vl a dependency and also removed the Vega typings. Now things should just work.

**Comment by chadbr** [comment]
Sorry, meant to follow up... working great.

**Comment by domoritz** [comment]
I'm glad it works.
