### ISSUE TITLE
Add link to bl.ocks.org example

### ISSUE THREAD

**Issue by curran** [vega/vega-embed#54]
Just a suggestion, it would be great to see this working on bl.ocks.org, so it would be easy for folks using that system to fork and modify examples.

Here's an example that exists already: https://bl.ocks.org/amitkaps/fe4238e716db53930b2f1a70d3401701

**Comment by domoritz** [comment]
Thanks for the suggestion. I added it.

**Comment by curran** [comment]
@domoritz Awesome! Thank you.
