### ISSUE TITLE
vega-embed cdn issue?

### ISSUE THREAD

**Issue by eytanadar** [vega/vega-embed#557]
I'm just cross-connecting this to something I posted for Altair. There might be a deployment issue for the vega-embed library on the CDN.

https://github.com/altair-viz/altair/issues/2280#issue-695987288

-E

**Comment by domoritz** [comment]
Thanks for posting it. I am looking into it.

**Comment by domoritz** [comment]
Hmm, I don't see any obvious problems with the deployment. https://observablehq.com/@vega/hello-vega-embed also works fine.

**Comment by domoritz** [comment]
Please try Vega-Embed 6.12.2 and let me know whether it works.

**Comment by domoritz** [comment]
If yes, then the fix was https://github.com/vega/vega-embed/commit/2fb713737b9747b63d90ff5e6eb1fe3c1794a369.

**Comment by domoritz** [comment]
Working again now.

**Comment by afonit** [comment]
Checking to see if anyone else is getting these again, since Friday I have been getting them.

```
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/vega.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/vega-embed.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

I have cleared cache, tried different browsers/computers and the result is the same.

**Comment by domoritz** [comment]
@afonit these links are for the sourcemaps and also look like they are missing a `vega/` in them. It should be https://cdn.jsdelivr.net/npm/vega/build/vega.min.js.map. Where do you see these warnings?

**Comment by afonit** [comment]
@domoritz 
those show up in the chrome dev console window when I serve notebooks through voila:
https://github.com/altair-viz/altair/issues/2298

I just started getting the errors on Friday.

**Comment by domoritz** [comment]
I see. Same as https://github.com/altair-viz/altair/issues/2298#issuecomment-699030384. I don't know about voila and would check with them. https://cdn.jsdelivr.net/npm/vega/build/vega.min.js.map works so the problem is the link to the resource that is wrong.

**Comment by afonit** [comment]
ok, I thought that vega-embed/altair was emitting that url - so you are saying voila is mangling the url?  Thanks for taking a look, I will continue to run it down on voila's end.

**Comment by domoritz** [comment]
Ah, so sourcemaps are only used for debugging and usually the js file links to the sourcemap file. 

<img width="1231" alt="Screen Shot 2020-09-28 at 07 40 24" src="https://user-images.githubusercontent.com/589034/94446789-f477a480-015d-11eb-84a8-22d8c49de560.png">

I suspect that voila is using https://cdn.jsdelivr.net/npm/vega, which then means that the sourcemap links to https://cdn.jsdelivr.net/npm/vega.js.map. There isn't much we can do since that's just how URIs work. Voila could refer to https://cdn.jsdelivr.net/npm/vega/build/vega.min.js and the right sourcemaps would be loaded.

**Comment by afonit** [comment]
I realized I had changed quite a few things at once, and I needed to start from scratch and see what item specifically may be contributing to the issue.

The first thing I tried, looks like it is it.

I was on voila **0.1.23**

So I have that version on my local instance, and the plots show up fine with voila.

Then I **upgrade voila to 0.2.3** and the plots do not show up:
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://ndjpnladcallmjemlbaebfadecfhkepb/editor/config.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://ndjpnladcallmjemlbaebfadecfhkepb/editor/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/vega.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
x_voila_altair_text.ipynb:290 Uncaught (in promise) ReferenceError: vegaEmbed is not defined
    at x_voila_altair_text.ipynb:290
(anonymous) @ x_voila_altair_text.ipynb:290
Promise.then (async)
(anonymous) @ x_voila_altair_text.ipynb:290
(anonymous) @ x_voila_altair_text.ipynb:292
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/vega-embed.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
main.js?v=9de22d21d90835225053df83a51fd350:13 Uncaught (in promise) TypeError: voila.connectKernel is not a function
    at main.js?v=9de22d21d90835225053df83a51fd350:13
    at main.js?v=9de22d21d90835225053df83a51fd350:55
    at Object.execCb (require.min.js:1)
    at b.check (require.min.js:1)
    at b.<anonymous> (require.min.js:1)
    at require.min.js:1
    at require.min.js:1
    at each (require.min.js:1)
    at b.emit (require.min.js:1)
    at b.check (require.min.js:1)
(anonymous) @ main.js?v=9de22d21d90835225053df83a51fd350:13
(anonymous) @ main.js?v=9de22d21d90835225053df83a51fd350:55
execCb @ require.min.js:1
check @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
each @ require.min.js:1
emit @ require.min.js:1
check @ require.min.js:1
enable @ require.min.js:1
init @ require.min.js:1
h @ require.min.js:1
completeLoad @ require.min.js:1
onScriptLoad @ require.min.js:1
load (async)
req.load @ require.min.js:1
load @ require.min.js:1
load @ require.min.js:1
fetch @ require.min.js:1
check @ require.min.js:1
enable @ require.min.js:1
enable @ require.min.js:1
(anonymous) @ require.min.js:1
(anonymous) @ require.min.js:1
each @ require.min.js:1
enable @ require.min.js:1
init @ require.min.js:1
(anonymous) @ require.min.js:1
setTimeout (async)
req.nextTick @ require.min.js:1
o @ require.min.js:1
requirejs @ require.min.js:1
(anonymous) @ main.js?v=9de22d21d90835225053df83a51fd350:10
favicon.ico:1 GET http://localhost:8866/favicon.ico 404 (Not Found)
```
