### ISSUE TITLE
some vega-lite config not respected with vegaEmbed

### ISSUE THREAD

**Issue by timelyportfolio** [vega/vega-embed#57]
Not sure if #3 is related, but some `vega-lite` config allowed with `vl.compile(spec,, {config})` are not respected, since [line](https://github.com/vega/vega-embed/blob/master/src/embed.ts#L104) does not compile/`PREPROCESSOR` using the config.  More specifically, the default mark color cannot be changed.   Mark `fill` is populated after compile/preprocess of the vega-lite spec, and the `config` will not override when `vega.parse` for runtime in [line](https://github.com/vega/vega-embed/blob/master/src/embed.ts#L126). 

Two workarounds are add `config` within the `vega-lite` spec or manually `vl.compile(spec, {config})` before passing to `vegaEmbed`.  These workarounds are certainly reasonable options, so I understand if this is just closed and serves as information for other users later.

### Example
reproducible [example](https://bl.ocks.org/timelyportfolio/318837735807cc53a2c5921de2a640ca/691c7081a879531682507e3d3bff7748e4f5408d) to help explain.

**Comment by domoritz** [comment]
As far as I can see it, config is only passed to Vega. So no Vega-Lite configs work.

Can you send a PR to fix this?

**Comment by timelyportfolio** [comment]
@domoritz thanks for the fix https://github.com/vega/vega-embed/commit/fe4c0d8ad9969d9d6f9ddc2550501985aa00c658.  I'll keep working on my Typescript skills so maybe next time I can close on my own :)

**Comment by domoritz** [comment]
No problem. Thanks for noting the issue and sending a pr!
