### ISSUE TITLE
Tooltips behaving differently when embedded in a larger page.

### ISSUE THREAD

**Issue by jeremysalwen** [vega/vega-embed#576]
I am trying to use vegaEmbed to embed visualizations in Tensorboard.  The basic chart is working correctly, but the tooltips seem to be broken when I use Vega-Embed from within my Svelte app.

For one subchart, the tooltip is not updating to the nearest point, and for another subchart, the tooltip is not appearing at all.

I can see that the tooltip works fine in the online editor, or even if I load it with Vega Embed using a simple demo page.  (spec: https://gist.githubusercontent.com/jeremysalwen/5f0fa14fa761b8775720df8ce03fa2e3/raw/7dd9d61ec2376e280c8abf552cd78ac381b7766d/spec.json)

I normally would not report this sort of bug because this sort of bug is usually a user issue.  However, in this case, the way that I am using Vega-Embed is so simple and self contained, I don't see how it could be anything but a bug in the library.  My only interaction with the Vega-Embed library is to call:

```
vegaEmbed("#chrt", JSON.parse(stepToChart[selectedStep]), {actions: false}).catch(error => console.log("VegaEmbedError: ", error));
```
which displays the chart, but with a broken tooltip.

You can see the full code here: https://github.com/JDBumgardner/stone_ground_hearth_battles/tree/master/tensorboard_vega_embed/tensorboard_vega_embed/svelte_frontend

**Comment by domoritz** [comment]
Hi @jeremysalwen. I'm having some trouble exactly following what the issue is. Can you try to reproduce the issue in a minimal web application (without any frameworks) and put it online (e.g. with https://bl.ocks.org/)?

Unfortunately, I don't have the cycles to run any setup to reproduce and debug this issue.

**Comment by jeremysalwen** [comment]
Well, on a whim, I upgraded my vega, vega-lite, and vega-embed dependencies, and now the bug is fixed.

**Comment by domoritz** [comment]
🎉
