### ISSUE TITLE
Vega embed instalation

### ISSUE THREAD

**Issue by amsuk47** [vega/vega-embed#59]
While installing npm, I got errors...I installed Net Framework 2.0 SDK, I still get same errors. Can someone help me with?
![image](https://user-images.githubusercontent.com/36973617/36876048-3d7f7588-1d70-11e8-840b-11bdfa129744.png)

**Comment by domoritz** [comment]
Can you use the linux subsystem and build there? I've used it before and it worked. I can't really help with the other issue.

**Comment by amsuk47** [comment]
was using window command line...is Linux subsystem in Windows 10?

**Comment by domoritz** [comment]
Yes.

**Comment by amsuk47** [comment]
Hmm...mine is Window 7
