### ISSUE TITLE
Scrollbars in observable

### ISSUE THREAD

**Issue by Maartenvm** [vega/vega-embed#592]
As mentioned in 
https://talk.observablehq.com/t/overflow-scroll-bars-showing-up-on-vega-embeds/1572
Scrollbars are added to observable embeds, which are unfortunate. 

According to Mike Bostock _"It’s the little (…) menu with the Save as / Open in Vega Editor links. If the chart is full-width, then the popup menu vega-embed adds will cause the chart to be wider than the page, and hence the scrollbar."_

The are even showing up in your own observable example page https://observablehq.com/@vega/hello-vega-embed
I would say the scrollbars are marring your otherwise excellent library's output.

**Comment by domoritz** [comment]
I don't see scrollbars on MacOS. What OS are you on? Can you help me reproduce the issue or even send a pull request to fix it?

<img width="1077" alt="Screen Shot 2020-11-05 at 07 10 57" src="https://user-images.githubusercontent.com/589034/98258714-0eaf5a00-1f36-11eb-887c-4b0a31308f97.png">

**Comment by Maartenvm** [comment]
I'm on windows, where 2 browsers show the same thing.

This is Edge 
![image](https://user-images.githubusercontent.com/1705817/98259447-712e4780-1f82-11eb-8f56-38b7b6f53437.png)

Chrome
![image](https://user-images.githubusercontent.com/1705817/98259404-5fe53b00-1f82-11eb-9082-3e117ad4cf84.png)

**Comment by domoritz** [comment]
I see. I don't have a window machine so I can't reproduce the issue. Can you try to debug which css properties might be causing the problem? You can do that with the browser inspector tool.

**Comment by Maartenvm** [comment]
Well it disappears if i change the vega-embed-wrapper overflow to hidden like:

.vega-embed-wrapper {
    max-width: 100%;
    overflow: hidden;
    padding-right: 14px;
}

But that has consequences. 

Though I think mbostock's answer already gave you another possibility, which is to move the location of the open (...) menu more to the left, so that it overlaps the already drawn chart instead of opening outside the chart?

**Comment by Maartenvm** [comment]
Wait, better solution. I think you're good if you put the overflow on auto. Works on both Edge and Chrome at least, and it preserves the horizontal scrollbar on this one:

![image](https://user-images.githubusercontent.com/1705817/98263891-9b363880-1f87-11eb-83c7-60eaada07891.png)

**Comment by domoritz** [comment]
Thanks for looking into it. So this should fix it https://github.com/vega/vega-embed/pull/593?

**Comment by Maartenvm** [comment]
It looks like it should, if that doesn't mess up anything on your end.

**Comment by domoritz** [comment]
I have to test it.

**Comment by domoritz** [comment]
Can you try the latest version?

**Comment by Maartenvm** [comment]
All fixed, thanks!

**Comment by Maartenvm** [comment]
PS: you might want to update your example notebooks to take advantage of the newest version now.

**Comment by domoritz** [comment]
> PS: you might want to update your example notebooks to take advantage of the newest version now.

It will actually use the latest version automatically. However, the CDN and your browser cache for a bit so it will take a few hours usually.
