### ISSUE TITLE
Localize hover text on vega actions button

### ISSUE THREAD

**Issue by lcvriend** [vega/vega-embed#597]
Thank you for your amazing work!

I am trying to localize the vega actions button. With the `i18n` property I can conveniently map the action strings to my native language which is awesome! However, I would also like to change the hover text "Click to view actions" on the button itself. In the generated `html` this hover text is set in the `title` attribute of the `details` tag. I can't seem to find a property to customize this.

Is it possible to localize this hover text using the embed options?

**Comment by domoritz** [comment]
Isn't that https://github.com/vega/vega-embed/blob/master/src/embed.ts#L56?

**Comment by lcvriend** [comment]
Wonderful! Thank you so much for pointing this out to me.

The option is a bit hidden as it is missing in the documentation. Perhaps it could be added to the README?
