### ISSUE TITLE
Installation troubles due to vega's optional canvas dependency

### ISSUE THREAD

**Issue by colehaus** [vega/vega-embed#60]
Same issue that lead to the creation of `vega-lib`. I have made and published my own fork of `vega-embed` that depends on `vega-lib` instead of `vega` (See https://github.com/colehaus/vega-embed and https://www.npmjs.com/package/vega-lib-embed/.). This is probably not a great long-term solution and it would be nice to upstream these changes somehow. However, I'm not sure what backwards-compatibility guarantees you all need to provide.

**Comment by domoritz** [comment]
I think evga-embed can just depend on vega-lib. Can you send a PR?

**Comment by colehaus** [comment]
Thanks!

**Comment by domoritz** [comment]
I fixed it. It should work now.
