### ISSUE TITLE
How to auto resize canvas in observable?

### ISSUE THREAD

**Issue by katopz** [vega/vega-embed#612]
I try to use `width: "container",` but canvas width appear to be `0` for some reason.

### What happen
![image](https://user-images.githubusercontent.com/97060/103544525-d0e99600-4ed2-11eb-9b53-136a1f87d6b3.png)

### Expectation
![image](https://user-images.githubusercontent.com/97060/103553802-8b33ca00-4ee0-11eb-9d76-0648cb467531.png)

```
{
    width: 100%;
    height: auto;
}
```

### Work around
```js
[...document.getElementsByClassName("marks")].map(e=>{e.style.width = "100%";e.style.height = "auto"})
```

### Demo
https://observablehq.com/@katopz/hello-vega-embed

BTW : I'm not sure this is vega or observable issue, but I can change canvas style to make it work maybe we can resolve via vega.

**Comment by domoritz** [comment]
Thank you for the issue report. Yes, I think we can make the behavior better in Vega Embed. The important thing is to make sure that we don't break anything else so I would love your help with this issue. 

First, can you take a look at https://github.com/vega/vega-embed/issues/584 and see whether it's related. 

Second, can you send a pull request with a working version. I am happy to take it for a spin to make sure we don't have any regressions. 

Thank you @katopz!

**Comment by domoritz** [comment]
Is this still an issue? If so, please respond with details and I will reopen.
