### ISSUE TITLE
Issue with clip=True from Altair?

### ISSUE THREAD

**Issue by sderuiter** [vega/vega-embed#62]
Hi,

I've tried the following Altair code in a Jupyter Lab - Notebook.
```
chart = alt.Chart(data).mark_bar(clip=True).encode(
    y=alt.Y('name:O', sort= {"op": "mean", "field": "utilization:Q"}),
    x=alt.X('utilization',  scale=alt.Scale(domain=[0,1])),
    color='rank:N',
).to_dict()
```
This outputs the following JSON:

```
{'$schema': 'https://vega.github.io/schema/vega-lite/v2.json',
 'config': {'view': {'height': 300, 'width': 400}},
 'data': .....,
 'encoding': {'color': {'field': 'rank', 'type': 'nominal'},
  'x': {'field': 'utilization',
   'scale': {'domain': [0, 1]},
   'type': 'quantitative'},
  'y': {'field': 'name',
   'sort': {'field': 'utilization:Q', 'op': 'mean'},
   'type': 'ordinal'}},
 'mark': {'clip': True, 'type': 'bar'}}
```
This chart is correctly displayed in Jupyter. However, I have exactly the same code in Python (3.6.4), using Vega-Embed to render my svg. 

The browser returns the following error message:
`Uncaught ReferenceError: True is not defined`

Not sure I fully understand the issue, but should this be a true (lowercase) for Javascript?

Using vega3==0.5.0, vega==0.4.4, altair==2.0.0rc1.

Thank you.

**Comment by domoritz** [comment]
JavaScript uses `true` instead of `True`. I hope this helps.

**Comment by sderuiter** [comment]
That is precisely the issue. As I am using Altair, I need to set `clip=True`, as `true` is not recognized in Python.
As the JSON output in Jupyter outputs  `'mark': {'clip': True, 'type': 'bar'}}` (and this renders the chart correctly), I'm assuming that the Vega-Lite spec requires `True`. 
As my Altair code also also outputs  `'mark': {'clip': True, 'type': 'bar'}}`, I'm assuming that a translation from `True `to `true` is mssing in Vega-Embed?

**Comment by domoritz** [comment]
When Python translates the dictionary to JSON, it converts `True` to `true`. I'm not sure whether your code above is actually the JSON output. JSON uses `"` instead of `'`.

**Comment by jakevdp** [comment]
If you want to output an Altair chart to json. use ``to_json()``.

``to_dict()`` outputs to a Python dict, which will not be valid json.

**Comment by domoritz** [comment]
Oh, now I see it! Thank you @jakevdp!

**Comment by sderuiter** [comment]
Thank you!
