### ISSUE TITLE
Custom loader target does not work

### ISSUE THREAD

**Issue by domoritz** [vega/vega-embed#625]
See https://github.com/vega/vega-lite/issues/3795#issuecomment-770437336

**Comment by domoritz** [comment]
Oh, we create the loader before we parse the spec because the spec may be a string and therefore we need a loader...

**Comment by domoritz** [comment]
How does https://github.com/vega/vega-embed/pull/626/files look to you @kennybui-data-ai?

**Comment by kennybui-data-ai** [comment]
I'm not a ts SME by any means but I think that logic looks correct to me. and the test case passed :)
