### ISSUE TITLE
View class as option

### ISSUE THREAD

**Issue by danmarshall** [vega/vega-embed#656]
Hello, I have a custom Vega View class [{vega-deck.gl}](https://github.com/microsoft/SandDance/tree/master/packages/vega-deck.gl#usage) which I would like to use with Vega within an [Idyll](https://github.com/idyll-lang/idyll) document. In this scenario, the dependency chain is:

idyll / idyll-vega-lite / react-vega / vega-embed

Vega-embed instantiates the View class here: https://github.com/vega/vega-embed/blob/master/src/embed.ts#L351

Would it be feasible to add the View class as an option in [EmbedOptions](https://github.com/vega/vega-embed/blob/master/src/embed.ts#L64)?

**Comment by domoritz** [comment]
Definitely. Please send a pull request.

Another option may be to not load Vega and implementing `vega.View` but I can see how that could be a challenge in your example.
