### ISSUE TITLE
Interactions not working anymore after applying changeset

### ISSUE THREAD

**Issue by BloodWorkXGaming** [vega/vega-embed#670]
Hello, I noticed an wierd interaction when using a brush in combination with streaming data.

When initally creating the vega instance I can interact with it just like expected: I can select a area fluently.

However after applying/running a changeset I loose this ability completely. Interacting with the chart is very laggy and I have to click it plenty of times before the brush even appears. Meanwhile the rest of the website is running completely smooth without any hickups.

I'm not expecting it to be performance issue, as throwing away the vega-embed instance and embedding a new one every refresh allows interactions again, which should have a much worse performance.

It is this a know problem or anything I have to call for it to work again? Would be thankful for any help :)

**Comment by domoritz** [comment]
Thanks for the bug report. Could you file a detailed report in the Vega repo at https://github.com/vega/vega?
