### ISSUE TITLE
es5-build file has spread operator in code (and erroring in IE 11)

### ISSUE THREAD

**Issue by pydolan** [vega/vega-embed#684]
I'm seeing  a "Syntax error" at line 11, column 3240, which in the minified file - https://cdn.jsdelivr.net/npm/vega-embed@6/build-es5/vega-embed.min.js - is the spread operator in this code:

```js
/\bsemver\b/i.test(process.env.NODE_DEBUG)?(...e)=>console.error("SEMVER",...e):()=>{},G=function(
```

Or in the non-minified file - https://cdn.jsdelivr.net/npm/vega-embed@6.17.0/build-es5/vega-embed.js - looks like the code is this:

```js
 const debug = (
    typeof process === 'object' &&
    process.env &&
    process.env.NODE_DEBUG &&
    /\bsemver\b/i.test(process.env.NODE_DEBUG)
  ) ? (...args) => console.error('SEMVER', ...args)
    : () => {};
```

Is some 3rd party code not being transpiled?

**Comment by domoritz** [comment]
Actually, a simple fix may be to use https://github.com/wessberg/rollup-plugin-ts#using-the-plugin-with-typescript-but-without-browserslists instead of browserslists.

**Comment by pydolan** [comment]
Understandable about dropping the ES5 support.  I'll see what I can do about resolving this issue.

I played around with it a bit, and I *think* the project's `babel.config.js` is being used behind the scenes by rollup (of course, it could be ignorance on my part about how this works). 

I tried adding this to the `ts()` config, but then I ran into the "deoptimizePath" issue you posted about on [here](https://github.com/rollup/rollup/issues/4067):
```js
    transpiler: "babel",
    babelConfig: {"presets": ["@babel/preset-env"], "targets": "defaults"},
```

**Comment by domoritz** [comment]
Ohhh, that would make sense. We need the babel config for jest so we should ignore that for the build. 

To fix https://github.com/rollup/rollup/issues/4067, you can use an older version of rollup. Feel free to pin to a previous version for now.
