### ISSUE TITLE
Vega Embed has javascript error with Tooltips

### ISSUE THREAD

**Issue by jploudre** [vega/vega-embed#72]
I'm using Altair to create html files that use Vega-Embed and hoping to get tooltips working. With versions 3.7 to 3.9 (current) they all throw this error:

> JavaScript Error: m.tooltip is not a function. (In 'm.tooltip(g)', 'm.tooltip' is undefined)

Not sure if it's needed but here's the relevant code from Altair's export (with data removed):

```
  <div id="vis"></div>
  <script type="text/javascript">
	var spec = (excerpted here since it has tons of data.)
    var embed_opt = {"mode": "vega-lite"};

    function showError(el, error){
        el.innerHTML = ('<div class="error">'
                        + '<p>JavaScript Error: ' + error.message + '</p>'
                        + "<p>This usually means there's a typo in your chart specification. "
                        + "See the javascript console for the full traceback.</p>"
                        + '</div>');
        throw error;
    }
    const el = document.getElementById('vis');
    vegaEmbed("#vis", spec, embed_opt)
      .catch(error => showError(el, error));
  </script>
```

**Comment by domoritz** [comment]
Do you use the notebook or Jupyterlab? Which version of vega3 if you use the notebook?

**Comment by jploudre** [comment]
Upgrading to latest Vega3 resolves this. Perfect!

Thanks again for all the hard work on this.
