### ISSUE TITLE
Add "Save as HTML" action

### ISSUE THREAD

**Issue by yuj** [vega/vega-embed#765]
Today there are "Save as SVG" and "Save as PNG" actions.  Sometimes, it would be useful to be able to "Save as HTML", so you can download an HTML file with the chart embeded that you can pass around and interact with.

**Comment by domoritz** [comment]
I think the open in editor action serves that purpose already. You can share via url from the editor. 

We could also add an html download to the editor.

**Comment by yuj** [comment]
@domoritz hosting data on url is not the approach we'd like to take. We prefer to embed the data along with the chart for convenience.  By the way, I've created a feature issue in the "editor" project:  https://github.com/vega/editor/issues/1086
