### ISSUE TITLE
Spec version warnings

### ISSUE THREAD

**Issue by ankane** [vega/vega-embed#767]
Hi, when running [the HTML](https://vega.github.io/vega-lite/tutorials/getting_started.html#embed) from the Vega-Lite tutorial, vega-embed shows two warnings about the spec version.

```text
The input spec uses Vega-Lite v5, but the current version of Vega-Lite is v5.1.1. vega-embed@6.18.2:21:8121
The compiled spec uses Vega v5, but current version is v5.20.2. vega-embed@6.18.2:21:8553
```

It shows the same warnings with the latest version of vega-embed (6.19.1). Since everything is v5, it seems like there probably shouldn't be any warnings.

**Comment by p-himik** [comment]
Just want to add that the warnings are there even if the versions are _exactly_ the same:
```
vega-embed.js:5639 The input spec uses Vega v5.21.0, but the current version of Vega is v5.21.0.
```

**Comment by domoritz** [comment]
Hmm, we get a crash in `semver` "TypeError: Right-hand side of 'instanceof' is not an object at new Range$a (http://localhost:3000/build/vega-embed.js:2712:19) at Object.satisfies$3 [as satisfies] (http://localhost:3000/build/vega-embed.js:3294:17) at guessMode (http://localhost:3000/build/vega-embed.js:5667:21) at _embed (http://localhost:3000/build/vega-embed.js:5802:20) at embed (http://localhost:3000/build/vega-embed.js:5736:20) at async run (http://localhost:3000/test-vl.html:55:24)"

**Comment by domoritz** [comment]
This seems to be a bug in the bundler and not Vega-Embed. See https://github.com/npm/node-semver/issues/381

**Comment by ankane** [comment]
Thanks @domoritz, that fixed it!
