### ISSUE TITLE
Reset the view

### ISSUE THREAD

**Issue by domoritz** [vega/vega-embed#80]
It would be great to have an action to reset the view to the initial state. One option may be to save the state in the beginning and then apply it again when the user wants to reset the chart. I don't know how this interacts with streaming data.

**Comment by jheer** [comment]
Yes, the Vega View `getState` and `setState` methods could be used to implement this feature. I'm not sure if streaming data should be an immediate concern here -- by default, it might make sense to have the View "reset" the settings but keep the current datasets. However, a complication is that signal values may be parameterized relative to the data, leading to an undesirable state when `setState` updates the signals to now outdated values. OTOH, I don't know if this case is common enough to stand in the way of an initial feature offering.

**Comment by domoritz** [comment]
I agree. I'll close this issue but we can revisit this discussion if it comes up again. cc @jakevdp
