### ISSUE TITLE
Implicit Dependency on using a CSS loader or Ignoring CSS

### ISSUE THREAD

**Issue by rgbkrk** [vega/vega-embed#83]
Recently our builds started to fail because `vega-tooltip` is `import`ing css. To get around this, we set up css ignores for the apps that were failing. I'm not sure if this was on purpose. If it is, what are the recommended approaches for loading the CSS?

Admittedly, we're probably going to vendorize your CSS, including it in a [styled-jsx tag](https://github.com/zeit/styled-jsx).

**Comment by domoritz** [comment]
Sorry for breaking your build. What build system do you use? Rollup, webpack, parcel?

**Comment by rgbkrk** [comment]
webpack

**Comment by domoritz** [comment]
Ahh, you need to a css loader so that webpack knows how to handle it: https://github.com/vega/editor/blob/7eb3d48cb647c47a46cbb929e45ef83fd890b80b/webpack.config.js#L34. Parcel should just work.

**Comment by domoritz** [comment]
It would be sweet if you could add a note to the embed docs about this.

**Comment by rgbkrk** [comment]
Thanks for the notes!

We also use the same package in Hydrogen (via Atom) and don't use a loader there. For now I'm just going to pin back a couple version so it doesn't break in userspace.

**Comment by domoritz** [comment]
If you import tooltip directly, you could instead require the bundled file and everything will just work. 

Another solution is to create a js with the css in it rather that importing css. However, that will require another preprocessing step here.

**Comment by rgbkrk** [comment]
We don't import tooltip directly, it comes by way of `vega-embed`. 

> Another solution is to create a js with the css in it rather that importing css. However, that will require another preprocessing step here.

Yeah we'll likely do that for our own library. We'll have to stay pinned for now until css imports are not an implicit dependency.

**Comment by domoritz** [comment]
I'm happy to accept pull requests here for a solution that doesn't import CSS directly. vega-Embed in the latest version also uses css imports by the way.

**Comment by rgbkrk** [comment]
I don't have any non React-centric CSS-in-JS methods of embedding that CSS, so I won't be able to help.

One solution would be to not do the import inside of `vega-tooltip` then document across all dependent packages how to import the classes you want applied.

**Comment by domoritz** [comment]
I don't think that's an option as it puts too much burden on the users. The solution is to write a script that creates a style.js file that has the style as a constant in it.

**Comment by domoritz** [comment]
I'm seeing problems in webpack based builds with including the style via import. They automatically add the stylesheet even if it's not used. 

So this issue needs to be fixed. I propose some kind of preprocessing step to convert the css file to js with an embedded string.

**Comment by domoritz** [comment]
Fixed. Will make a release soon.

**Comment by rgbkrk** [comment]
Thanks!

**Comment by domoritz** [comment]
Deployed as embed 3.14
