### ISSUE TITLE
WARN: xOffset-encoding is dropped as xOffset is not a valid encoding channel.

### ISSUE THREAD

**Issue by nholland20** [vega/vega-embed#842]
I am attempting to use xOffset to jitter my x-axis values as described here: https://vega.github.io/vega-lite/docs/encoding.html#position-offset. 
It is working when I use the VS Code vega viewer; however, it is not working when I use vega-embed. 
Example usage:
{"$schema": "https://vega.github.io/schema/vega-lite/v5.json",
        "data": {
            "url": "data/psuedo_data_for_plotting_practice.csv"
        },
        "transform": [{"calculate": "random()", "as": "random"}],
        "mark": {
            "type": "point",
            "filled": true,
            "tooltip": true
        },
        "encoding": {
            "x": {
                "field": "primary_location",
                "type": "nominal"
            },
            "y": {
                "field": "GenesDetected",
                "type": "quantitative"
            },
            "xOffset": {
                "field": "random",
                "type": "quantitative"
            },
          "color": {
                "field": "secondary_location",
                "type": "nominal"
           }
}

**Comment by domoritz** [comment]
Please provide a full working example including the html

**Comment by nholland20** [comment]
I'm not sure how I can provide the working example as it is only working in the VS Code extension.
vega-embed is being called with this code: 
try {
    return embed(`#${id}`, visdata, {
      actions: false,
      theme: 'dark'
    })

**Comment by domoritz** [comment]
Send a full HTML page with a minimal example.

**Comment by una-dinosauria** [comment]
This is not a vega-embed issue. The error comes from `vega-lite`, more specifically, [the `isChannel` function](https://github.com/vega/vega-lite/blob/16bc9138a2470274f2a2e6c964b9a03822c7dd5c/src/channel.ts#L206-L208) decides if a channel is valid for the latest grammar.

Upgrading vega to `5.21.0` and `vega-lite` to `5.2.0` (both latest at the time of this writing) solved the issue for me.
