### ISSUE TITLE
same `config` object ignored when switching from vega to vega-lite

### ISSUE THREAD

**Issue by Casyfill** [vega/vega-embed#85]
Here is the javascript code:
```
const spec1 = "specs/timeline.vg.json";

opt = {"actions":false,
               "renderer": 'svg', "config": SETheme, 
               "padding": {"left": 5, "top": 5, "right": 5, "bottom": 5}
      };

vegaEmbed('#vis', spec1, opt)
    .then(function(result) {
        VIEW = result.view;
        let element = $('div#vis');
        VIEW.width(element.width()).run();
    })
    .catch(console.warn);


$(window).on('resize', function() {
    let element = $('div#vis');
    VIEW.width(element.width()).run();
    })
```

both `timeline.vg.json` and `timeline.vl.json` are copies of [this example](https://vega.github.io/vega-lite/examples/interactive_overview_detail.html), in vega's case - compiled by the online editor;

and [here](https://gist.github.com/Casyfill/565accc0575f9a25a6d11c2d33b72d00) is the `SETheme` object.

Essentially when I switch from `timeline.vl.json` to `timeline.vg.json` my config styling drops...

**Comment by domoritz** [comment]
I cannot reproduce this. Can you give me a working example?

```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Vega-Embed for Vega</title>

  <script src="https://cdn.jsdelivr.net/npm/vega@3"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-embed@3"></script>
</head>

<body>
  <div id="vis"></div>
  <script type="text/javascript">
    var config = {
      background: "#efefef",
      axis: {
        labelFont: "serif",
        labelFontSize: 16,
        tickWidth: 3,
        tickColor: "red"
      }
    };
    vegaEmbed('#vis', 'https://vega.github.io/vega/examples/bar-chart.vg.json', { config: config, defaultStyle: true }).then(function (result) {
      console.log(result);
    }).catch(console.error);
  </script>
</body>

</html>
```

**Comment by Casyfill** [comment]
here is an example; same config, seemingly correct in terms of vega, does not work when I switch from timeline.vl.json to timeline.vg.json

https://gist.github.com/Casyfill/86a5d01ce817593639eff185c0b7a7c5

**Comment by domoritz** [comment]
Blockbuilder link: https://blockbuilder.org/Casyfill/86a5d01ce817593639eff185c0b7a7c5

**Comment by domoritz** [comment]
And my fork: http://blockbuilder.org/domoritz/71f37aafa0a45ed8cbcbf48ee3e9828e

**Comment by domoritz** [comment]
The problem is not Embed but the config itself. The config you wrote only works in Vega-Lite. 

Looks at what it get's compiled to

```json
"config": {
    "axisY": {"minExtent": 30},
    "style": {"area": {"fill": "#0195E5"}, "rect": {"fill": "#0195E5"}},
...
  }
```

**Comment by Casyfill** [comment]
does it mean I have to swap 2 config files if I want to support both vega and vega-lite in my app?

**Comment by domoritz** [comment]
No, Vega config files also work in Vega-Lite. However, Vega-Lite configs are a superset of Vega configs and so some features won't work in pure Vega unless you write you Vega in a particular way.

**Comment by Casyfill** [comment]
Ah, got it, thanks!
