### ISSUE TITLE
i18n support of actions

### ISSUE THREAD

**Issue by GCheung55** [vega/vega-embed#87]
The actions text are hardcoded in English. It would be useful to have the text localized or provide a mechanism for providing localized strings.

**Comment by domoritz** [comment]
Yes, it would be nice. I think we could just have a map of identifiers to the stings to use. Do you want to send a PR?

**Comment by GCheung55** [comment]
@domoritz Sure. Where would you suggest putting the map of identifiers?

I was thinking of sending it down as part of the `actions` option, but each key is expected to be a boolean. I was thinking of something like:

```javascript
{
    actions: {
        export: {
            svg: {
                text: 'foo'
            }
        }
    }
}
```

Otherwise the alternative would be to add another option.

**Comment by domoritz** [comment]
I think I'd prefer a separate key.

```js
{
  i18n: {
    SVG_ACTION: "Save as SVG",
    PNG_ACTION: "Save as PNG"
  }
}
```
