### ISSUE TITLE
Re-render Vega-embed through Ajax call

### ISSUE THREAD

**Issue by sderuiter** [vega/vega-embed#89]
Hi,
Couldn't find any related info on this. 
I'm using Jquery to have a <div> re-rendered with an updated Django view that pulls data from a db, feeds this into Altair, which outputs a JSON spec for Vega-Lite, which is fed to a Vega-Embed object on (a portion of) a HTML page.

```
$.get("a_cp/"+s,
function(response) {
                $('.filtered_resources').html(response);
...
```

This works perfectly if I the content that needs to be updated is an HTML table. However, if I have a Vega-Embed object, the object will not re-render. I can see in Console that the correct, updated data is loaded into the spec constant.

```
<div id="viz"></div>
    
  <script>
       
    const spec =  {{ filtered_data|safe }};
    vegaEmbed('#viz', spec, {"mode": "vega-lite", "renderer": "svg", "width": 800, "height": 600, "actions":{export: false, source: false, editor: true} }).catch(console.warn);
    
</script>
```

I've tried a bunch of suggestions for getting the browser to redraw parts of the interface
`$('.filtered_resources').redraw();`
but that doesn't seem to work.

Question: is it possible to have the browser re-render the Vega-Embed object?

**Comment by domoritz** [comment]
As far as I know, Vega does not have a way to fetch data sources again. You need to write some warpper code that fetches the resource and then uses the Vega view API to set the data. You can create a feature request in the Vega repo.
