### ISSUE TITLE
Support view.hover hoverSet and leaveSet arguments.

### ISSUE THREAD

**Issue by GCheung55** [vega/vega-embed#90]
Currently `hover` option is a boolean, which triggers `view.hover` by default.

`view.hover` supports two arguments, hoverSet and leaveSet.

I'd like to use `vega-embed` with `ember-vega`, but require the support of `hoverSet` and `leaveSet` as an option.

In `ember-vega`, `enableHover` is the option that would trigger `view.hover`. `enableHover` can be a boolean or an object with `hoverSet` and `leaveSet` properties.

@domoritz what are your thoughts around making `hover` option either a boolean or an object?

**Comment by domoritz** [comment]
That makes a lot of sense. Can you send a PR?

For reference: https://vega.github.io/vega/docs/api/view/#view_hover

**Comment by domoritz** [comment]
Do you have this on your roadmap?

**Comment by GCheung55** [comment]
Yes but probably not for another month.

**Comment by domoritz** [comment]
@GCheung55 this month?

**Comment by GCheung55** [comment]
I've started implementing. Currently blocked by https://github.com/vega/vega-typings/pull/46

**Comment by domoritz** [comment]
Merged (with some changes) and released.

**Comment by GCheung55** [comment]
@domoritz Thanks! How do I go about updating `vega-typings` dependency since it's not listed in `package.json`?

**Comment by domoritz** [comment]
You update it with yarn.

**Comment by domoritz** [comment]
Done
