### ISSUE TITLE
Support setting data before run or runAsync is executed.

### ISSUE THREAD

**Issue by GCheung55** [vega/vega-embed#91]
`vega-embed` currently only supports inlined data in the spec. When the spec contains data with an empty values array with the intention of having data inserted with `changset` objects, the dimensions seems to be wrong.

Here's an example, where the Y-Axis is cut off.

https://bl.ocks.org/gcheung55/35ce59b3f3ecb67e069a97ad468b3125/0552aaf68b3d901e1cfb7dd9d73b6a3f7c42c1be

![image](https://user-images.githubusercontent.com/46033/42188837-71105ab6-7e0a-11e8-878a-8198cca06053.png)

A possible solution around this is to set the height and width again when the data change is made but this incurs a cost of executing functions unnecessarily.

Perhaps execute `run` or `runAsync` after a callback or an intermediate promise?

**Comment by domoritz** [comment]
> vega-embed currently only supports inlined data in the spec

That is not true. Vega embed supports inline data, data from URLs and named datasets just like Vega and Vega-Lite. 

When you add data, you need to run https://vega.github.io/vega/docs/api/view/#view_resize or add

```
autosize: {
  resize: true
},
```

to your spec. 

If the data is available at compile time, it's best to insert it into the spec. Vega-Lite has a top level datastore to make this easier.

**Comment by GCheung55** [comment]
I stand corrected on the "only supports inlined data" statement.

I'll consider how to include the executing `view.resize` when data changes.

For my scenario, while my demos have data available at compile time, I want to demonstrate how to insert data during runtime because the scenario I'm supporting deals with accessing multiple sources of data where the data can change over time.

**Comment by domoritz** [comment]
I'd either manually add padding so that the chart does not have to resize, manually call resize when data changes in a way that could trigger changes to the axis labels, or add `autosize.resize = true`.

**Comment by domoritz** [comment]
Closing as this issue is beyond Vega-Embed.
