### ISSUE TITLE
Finalize/Destroy?

### ISSUE THREAD

**Issue by bit-less** [vega/vega-embed#92]
I don't see a method to destroy/remove listeners.  Vega has `finalize()` but I don't see that behavior in the code for Vega Embed, or in the documentation for Vega Lite or Vega Embed.  I only work in large SPA webapps and don't want to rely on garbage collection.  Is there a method I'm missing, or something in the docs that addresses this?  Thanks.

**Comment by domoritz** [comment]
The promise returns a result, which gives you access to the Vega view that you can use to finalize. Does that work for you?

**Comment by bit-less** [comment]
Ah. I didn't realize that `result.view` was a Vega view.  Since I'm just getting into Vega (Lite) I assumed that that was an "Embed view" not, a Vega view.  Okay, so I could simply do `vegaEmbed('#vis', spec).then(function(result) { result.view.finalize(); }).catch(console.error);` if I wanted to destroy the listeners immediately after creating it?

It think it would be helpful to add a little section on the docs explaining that it returns an object with a Vega view that can be used for regular method calls if that's the case.

**Comment by bit-less** [comment]
Never mind.  Just found it!: `Returns a Promise that resolves to the instantiated Vega View instance and a copy of the parsed JSON Vega spec.`  https://github.com/vega/vega-embed#embed

**Comment by domoritz** [comment]
Yes, the code looks like what I meant.

The example in https://github.com/vega/vega-embed#basic-example also has a comment about the Vega view. 

Enjoy the Vega ecosystem!

**Comment by bit-less** [comment]
Yeah, that basic example is what I saw first, but I assumed it was an internal "view" object that was Embed-specific, and not a Vega view instance.  Thanks for the help!

BTW, I watched one of your presentation from last year.  You guys have done some some incredible work!

**Comment by domoritz** [comment]
Thank you! Which one was that?

**Comment by bit-less** [comment]
Vega Lite: A Grammar of Interactive Graphics - Wongsuphasawat, Moritz, and Satyanarayan
https://www.youtube.com/watch?v=9uaHRWj04D4
