### ISSUE TITLE
Internet Explorer Javascript Error: Object doesn't support 'startswith'

### ISSUE THREAD

**Issue by jploudre** [vega/vega-embed#94]
I'm trying to troubleshoot altair (vegalite) graphs in IE 11. I have the javascripts for IE compatibility installed on the page (promise, symbol, fetch javascripts).

I get the javascript error Object doesn't support startswith when it's detecting the beginning of the URL.

![image](https://user-images.githubusercontent.com/305291/43154256-96260d1c-8f28-11e8-86cd-0d71aa295015.png)

I don't have experience debugging in IE. Graphs work on Chrome, Safari, Mobile devices so this appears to be IE on Windows specific.

**Comment by domoritz** [comment]
Yeah, looks like it's not supported: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith.

**Comment by domoritz** [comment]
Fixed in 3.18.2. Can you give it a try (I don't have IE).

**Comment by jploudre** [comment]
Yes, fixed. (I don't have it except at work.)

Thanks!
