### ISSUE TITLE
Possible bug while rendering vega-lite bar chart

### ISSUE THREAD

**Issue by Mahesha999** [vega/vega-embed#940]
I have a JSON data of 55 students of the following form:

    [{ "student_name" : "student 0", "e" : "100.15", "d" : "127.81" }, { "student_name" : "student 1", "e" : "100.30", "d" : "189.94" }, ... ]

I created percentage cumulative frequency data out of it of the following form:

    cdf_data = [
      { d_percentages: 0, student_percentages: 35 },
      { d_percentages: 10, student_percentages: 42 },
      { d_percentages: 20, student_percentages: 55 },
      { d_percentages: 30, student_percentages: 75 },
      { d_percentages: 40, student_percentages: 85 },
      { d_percentages: 50, student_percentages: 91 },
      { d_percentages: 60, student_percentages: 96 },
      { d_percentages: 70, student_percentages: 98 },
      { d_percentages: 80, student_percentages: 98 },
      { d_percentages: 90, student_percentages: 100 },
      { d_percentages: 100, student_percentages: 100 }
    ]

Then I create vega-lite plot as follows:

```
cdf_plot = {
  const plot = vl.markBar()
    .data(cdf_data)
    .encode(
      vl.y()
        .fieldQ('student_percentages'),
      vl.x()
        .fieldQ('d_percentages')//.bin(true)
        .scale({ "domain": [0, 100] })
        .bin({ minbins: 10 })
    ).width(500).height(250);
  
  return plot.toObject();
}
```

When output with `vegalite(cdf_plot)`, it outputs this (which seems correct to me):

![image](https://user-images.githubusercontent.com/4706946/173306832-8ee7281f-7731-4156-8bba-2379d4eaa252.png)

But when output with `embed(cdf_plot)`, it outputs this (which doesnt seem correct to me for range `90-100`):

![image](https://user-images.githubusercontent.com/4706946/173306956-cfa19f9a-b278-453e-913e-7173ed1c2d60.png)

Have I dont some mistake here or its a bug?

PS: [Here](https://observablehq.com/d/85b5f9610c49a395) is the observablehq notebook rendering all this.

**Comment by domoritz** [comment]
Since you binned the data yourself, you should use binned. See https://vega.github.io/vega-lite/docs/bin.html#binned. 

What's happening is that you have 11 records but want 10 bins. The last bin includes more than one data item. 

I think the difference you see is because Vega fixed how the last bin is treated at some point.
