### ISSUE TITLE
Action menu ux

### ISSUE THREAD

**Issue by domoritz** [vega/vega-embed#95]
I sometimes want to click on the action menu when I forget that I only need to hover. Then I accidentally export the chart as svg. I think it would be good to have a noop where the original action button was.

**Comment by kanitw** [comment]
This happens to me so many times too.  I'd say that we should fix this soon as it's a pretty annoying user experience, even for ourselves.

**Comment by domoritz** [comment]
What's your suggestion? Just move the popup down a bit?

**Comment by arvind** [comment]
Or switch to a click.
