### ISSUE TITLE
CORS error when loading JSON from local file

### ISSUE THREAD

**Issue by alexandrehtrb** [vega/vega-embed#951]
Hello,

I would like to be able to load and render Vega views, loaded from a local file, when running from a static HTML page.

For example:

```html
<div class="vegalite" id="vegaliteView1"></div>
<script>vegaEmbed('#vegaliteView1','data/worldcup2018_group_F.vl.json');</script>
```

Error: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

Is it possible to do that? Can the vega-embed code be changed to accept local files?

Thanks in advance and congratulations on your work, it is very good.

**Comment by domoritz** [comment]
You need to run a local server. CORS is a browser restriction.
