### ISSUE TITLE
Tooltips not working as expected

### ISSUE THREAD

**Issue by tafsiri** [vega/vega-embed#96]
Hi, I've had a fair amount of trouble getting tooltips to work in a chart. I've made a codepen to demonstrate. https://codepen.io/tafsiri/pen/wEBdVo?editors=1011

I am following the description of tooltips here https://vega.github.io/vega-lite/docs/tooltip.html

* If I use `'mark': {'type': 'point', 'tooltip': {'content': 'data'}}`, then i get tooltips, but they just say "content: data" for each point
* If i don't include the `'tooltip': {'content': 'data'}` attribute in the mark spec then I don't get any tooltips, the docs seem to suggest that tooltips would be enabled by default and display all the properties of the underlying data.

Am I missing something on how to specify tooltips? Are there any differences when using vega-embed to be aware of?

**Comment by domoritz** [comment]
Sorry about the troubles. `'tooltip': {'content': 'data'}` in a Vega-Lite 3. Can you use Vega-Lite 3 and see whether the issues go away?

**Comment by domoritz** [comment]
You can use Vega-Lite 3 with Vega-Embed already but I should update the NPM package. I plan to have an RC version very soon but it won't have the final version of Vega-Lite 3, yet. Vega-Lite 3 final will not be before September. 

> Alternatively is there a quick way to get a tooltip displaying a couple of fields with vega-lite 2?

Yes, you can pass an array to the tooltip channel.
