### ISSUE TITLE
Support changed data in source, compiled, and editor actions

### ISSUE THREAD

**Issue by GCheung55** [vega/vega-embed#99]
The current implementation of the source, compiled, and editor actions will only use the `spec`. Any data changed on the view will not be included.

@domoritz What are your thoughts around getting the data from the `view` and setting it on a copy of the `spec` that is used as for the source, compiled, and editor actions?

**Comment by domoritz** [comment]
Hmm, then we should also pass signals to the editor. We could do that with get and setstate.

**Comment by seanlaff** [comment]
I'm using vega within a react app and usually my app will render the vega-embed on page load, and then fill it with data when the asynchronous data fetching handler returns. I mainly use the "view in editor" action to help me debug things. 

As a work around I run `JSON.stringify(myViewInstance.getState().data)) and copy the updated data into the vega sandbox.

**Comment by domoritz** [comment]
Thanks for the workaround @seanlaff! Ideally, Vega-Embed would tun this command, package up the state, and send it to the editor. I'd appreciate contributions along those lines.

**Comment by domoritz** [comment]
@jheer I tried to do this but ran into issues with `view.getState()`. Is the state supposed to be serializable? I got errors that the state object has cycles.

**Comment by jheer** [comment]
No, I don't think we can guarantee serializability to JSON. But I would need to look closer again. The state export can be configured, so there may be workarounds depending on what state you require and what state it might be safe to omit.

**Comment by domoritz** [comment]
This issue is blocked by https://github.com/vega/vega/issues/1730

**Comment by domoritz** [comment]
Closing since we can't do anything until Vega has a serializable state.
